// Generated from https://effect-ts.github.io/effect (API reference navigation).
// Package descriptions and thematic groupings are authored by hand.

export type ApiModule = { name: string; href: string };

export type ApiPackage = {
	slug: string;
	name: string;
	description: string;
	modules: ApiModule[];
	/** Optional thematic grouping of modules, keyed by group title. */
	moduleGroups?: { title: string; modules: string[] }[];
};

export const API_PACKAGES: ApiPackage[] = [
	{
		slug: "cli",
		name: "@effect/cli",
		description:
			"Build polished, type-safe command-line applications with arguments, options, and prompts.",
		modules: [
			{ name: "Args", href: "/docs/api/v3/cli/Args" },
			{ name: "AutoCorrect", href: "/docs/api/v3/cli/AutoCorrect" },
			{ name: "BuiltInOptions", href: "/docs/api/v3/cli/BuiltInOptions" },
			{ name: "CliApp", href: "/docs/api/v3/cli/CliApp" },
			{ name: "CliConfig", href: "/docs/api/v3/cli/CliConfig" },
			{ name: "Command", href: "/docs/api/v3/cli/Command" },
			{ name: "CommandDescriptor", href: "/docs/api/v3/cli/CommandDescriptor" },
			{ name: "CommandDirective", href: "/docs/api/v3/cli/CommandDirective" },
			{ name: "ConfigFile", href: "/docs/api/v3/cli/ConfigFile" },
			{ name: "HelpDoc", href: "/docs/api/v3/cli/HelpDoc" },
			{ name: "HelpDoc/Span", href: "/docs/api/v3/cli/HelpDoc/Span" },
			{ name: "index", href: "/docs/api/v3/cli/index" },
			{ name: "Options", href: "/docs/api/v3/cli/Options" },
			{ name: "Primitive", href: "/docs/api/v3/cli/Primitive" },
			{ name: "Prompt", href: "/docs/api/v3/cli/Prompt" },
			{ name: "Usage", href: "/docs/api/v3/cli/Usage" },
			{ name: "ValidationError", href: "/docs/api/v3/cli/ValidationError" },
		],
	},
	{
		slug: "cluster",
		name: "@effect/cluster",
		description:
			"Distributed computing with entities, sharding, singletons, and durable messaging.",
		modules: [
			{ name: "ClusterCron", href: "/docs/api/v3/cluster/ClusterCron" },
			{ name: "ClusterError", href: "/docs/api/v3/cluster/ClusterError" },
			{ name: "ClusterMetrics", href: "/docs/api/v3/cluster/ClusterMetrics" },
			{ name: "ClusterSchema", href: "/docs/api/v3/cluster/ClusterSchema" },
			{
				name: "ClusterWorkflowEngine",
				href: "/docs/api/v3/cluster/ClusterWorkflowEngine",
			},
			{ name: "DeliverAt", href: "/docs/api/v3/cluster/DeliverAt" },
			{ name: "Entity", href: "/docs/api/v3/cluster/Entity" },
			{ name: "EntityAddress", href: "/docs/api/v3/cluster/EntityAddress" },
			{ name: "EntityId", href: "/docs/api/v3/cluster/EntityId" },
			{ name: "EntityProxy", href: "/docs/api/v3/cluster/EntityProxy" },
			{
				name: "EntityProxyServer",
				href: "/docs/api/v3/cluster/EntityProxyServer",
			},
			{ name: "EntityResource", href: "/docs/api/v3/cluster/EntityResource" },
			{ name: "EntityType", href: "/docs/api/v3/cluster/EntityType" },
			{ name: "Envelope", href: "/docs/api/v3/cluster/Envelope" },
			{ name: "HttpRunner", href: "/docs/api/v3/cluster/HttpRunner" },
			{ name: "index", href: "/docs/api/v3/cluster/index" },
			{ name: "K8sHttpClient", href: "/docs/api/v3/cluster/K8sHttpClient" },
			{ name: "MachineId", href: "/docs/api/v3/cluster/MachineId" },
			{ name: "Message", href: "/docs/api/v3/cluster/Message" },
			{ name: "MessageStorage", href: "/docs/api/v3/cluster/MessageStorage" },
			{ name: "Reply", href: "/docs/api/v3/cluster/Reply" },
			{ name: "Runner", href: "/docs/api/v3/cluster/Runner" },
			{ name: "RunnerAddress", href: "/docs/api/v3/cluster/RunnerAddress" },
			{ name: "RunnerHealth", href: "/docs/api/v3/cluster/RunnerHealth" },
			{ name: "Runners", href: "/docs/api/v3/cluster/Runners" },
			{ name: "RunnerServer", href: "/docs/api/v3/cluster/RunnerServer" },
			{ name: "RunnerStorage", href: "/docs/api/v3/cluster/RunnerStorage" },
			{ name: "ShardId", href: "/docs/api/v3/cluster/ShardId" },
			{ name: "Sharding", href: "/docs/api/v3/cluster/Sharding" },
			{ name: "ShardingConfig", href: "/docs/api/v3/cluster/ShardingConfig" },
			{
				name: "ShardingRegistrationEvent",
				href: "/docs/api/v3/cluster/ShardingRegistrationEvent",
			},
			{ name: "SingleRunner", href: "/docs/api/v3/cluster/SingleRunner" },
			{ name: "Singleton", href: "/docs/api/v3/cluster/Singleton" },
			{
				name: "SingletonAddress",
				href: "/docs/api/v3/cluster/SingletonAddress",
			},
			{ name: "Snowflake", href: "/docs/api/v3/cluster/Snowflake" },
			{ name: "SocketRunner", href: "/docs/api/v3/cluster/SocketRunner" },
			{
				name: "SqlMessageStorage",
				href: "/docs/api/v3/cluster/SqlMessageStorage",
			},
			{
				name: "SqlRunnerStorage",
				href: "/docs/api/v3/cluster/SqlRunnerStorage",
			},
			{ name: "TestRunner", href: "/docs/api/v3/cluster/TestRunner" },
		],
		moduleGroups: [
			{
				title: "Entities",
				modules: [
					"Entity",
					"EntityAddress",
					"EntityId",
					"EntityProxy",
					"EntityProxyServer",
					"EntityResource",
					"EntityType",
					"Singleton",
					"SingletonAddress",
				],
			},
			{
				title: "Sharding",
				modules: [
					"Sharding",
					"ShardingConfig",
					"ShardingRegistrationEvent",
					"ShardId",
					"MachineId",
				],
			},
			{
				title: "Runners",
				modules: [
					"Runner",
					"RunnerAddress",
					"RunnerHealth",
					"Runners",
					"RunnerServer",
					"RunnerStorage",
					"HttpRunner",
					"SocketRunner",
					"SingleRunner",
					"TestRunner",
				],
			},
			{
				title: "Messaging",
				modules: [
					"Message",
					"MessageStorage",
					"Envelope",
					"Reply",
					"DeliverAt",
					"Snowflake",
				],
			},
			{ title: "Storage", modules: ["SqlMessageStorage", "SqlRunnerStorage"] },
			{
				title: "Cluster",
				modules: [
					"ClusterCron",
					"ClusterError",
					"ClusterMetrics",
					"ClusterSchema",
					"ClusterWorkflowEngine",
					"K8sHttpClient",
					"index",
				],
			},
		],
	},
	{
		slug: "effect",
		name: "effect",
		description:
			"The core Effect library \u2014 data types, concurrency, streams, scheduling, configuration, and more.",
		modules: [
			{ name: "Arbitrary", href: "/docs/api/v3/effect/Arbitrary" },
			{ name: "Array", href: "/docs/api/v3/effect/Array" },
			{ name: "BigDecimal", href: "/docs/api/v3/effect/BigDecimal" },
			{ name: "BigInt", href: "/docs/api/v3/effect/BigInt" },
			{ name: "Boolean", href: "/docs/api/v3/effect/Boolean" },
			{ name: "Brand", href: "/docs/api/v3/effect/Brand" },
			{ name: "Cache", href: "/docs/api/v3/effect/Cache" },
			{ name: "Cause", href: "/docs/api/v3/effect/Cause" },
			{ name: "Channel", href: "/docs/api/v3/effect/Channel" },
			{
				name: "ChildExecutorDecision",
				href: "/docs/api/v3/effect/ChildExecutorDecision",
			},
			{ name: "Chunk", href: "/docs/api/v3/effect/Chunk" },
			{ name: "Clock", href: "/docs/api/v3/effect/Clock" },
			{ name: "Config", href: "/docs/api/v3/effect/Config" },
			{ name: "ConfigError", href: "/docs/api/v3/effect/ConfigError" },
			{ name: "ConfigProvider", href: "/docs/api/v3/effect/ConfigProvider" },
			{
				name: "ConfigProviderPathPatch",
				href: "/docs/api/v3/effect/ConfigProviderPathPatch",
			},
			{ name: "Console", href: "/docs/api/v3/effect/Console" },
			{ name: "Context", href: "/docs/api/v3/effect/Context" },
			{ name: "Cron", href: "/docs/api/v3/effect/Cron" },
			{ name: "Data", href: "/docs/api/v3/effect/Data" },
			{ name: "DateTime", href: "/docs/api/v3/effect/DateTime" },
			{ name: "DefaultServices", href: "/docs/api/v3/effect/DefaultServices" },
			{ name: "Deferred", href: "/docs/api/v3/effect/Deferred" },
			{ name: "Differ", href: "/docs/api/v3/effect/Differ" },
			{ name: "Duration", href: "/docs/api/v3/effect/Duration" },
			{ name: "Effect", href: "/docs/api/v3/effect/Effect" },
			{ name: "Effectable", href: "/docs/api/v3/effect/Effectable" },
			{ name: "Either", href: "/docs/api/v3/effect/Either" },
			{ name: "Encoding", href: "/docs/api/v3/effect/Encoding" },
			{ name: "Equal", href: "/docs/api/v3/effect/Equal" },
			{ name: "Equivalence", href: "/docs/api/v3/effect/Equivalence" },
			{ name: "ExecutionPlan", href: "/docs/api/v3/effect/ExecutionPlan" },
			{
				name: "ExecutionStrategy",
				href: "/docs/api/v3/effect/ExecutionStrategy",
			},
			{ name: "Exit", href: "/docs/api/v3/effect/Exit" },
			{ name: "FastCheck", href: "/docs/api/v3/effect/FastCheck" },
			{ name: "Fiber", href: "/docs/api/v3/effect/Fiber" },
			{ name: "FiberHandle", href: "/docs/api/v3/effect/FiberHandle" },
			{ name: "FiberId", href: "/docs/api/v3/effect/FiberId" },
			{ name: "FiberMap", href: "/docs/api/v3/effect/FiberMap" },
			{ name: "FiberRef", href: "/docs/api/v3/effect/FiberRef" },
			{ name: "FiberRefs", href: "/docs/api/v3/effect/FiberRefs" },
			{ name: "FiberRefsPatch", href: "/docs/api/v3/effect/FiberRefsPatch" },
			{ name: "FiberSet", href: "/docs/api/v3/effect/FiberSet" },
			{ name: "FiberStatus", href: "/docs/api/v3/effect/FiberStatus" },
			{ name: "Function", href: "/docs/api/v3/effect/Function" },
			{ name: "GlobalValue", href: "/docs/api/v3/effect/GlobalValue" },
			{ name: "Graph", href: "/docs/api/v3/effect/Graph" },
			{ name: "GroupBy", href: "/docs/api/v3/effect/GroupBy" },
			{ name: "Hash", href: "/docs/api/v3/effect/Hash" },
			{ name: "HashMap", href: "/docs/api/v3/effect/HashMap" },
			{ name: "HashRing", href: "/docs/api/v3/effect/HashRing" },
			{ name: "HashSet", href: "/docs/api/v3/effect/HashSet" },
			{ name: "HKT", href: "/docs/api/v3/effect/HKT" },
			{ name: "index", href: "/docs/api/v3/effect/index" },
			{ name: "Inspectable", href: "/docs/api/v3/effect/Inspectable" },
			{ name: "Iterable", href: "/docs/api/v3/effect/Iterable" },
			{ name: "JSONSchema", href: "/docs/api/v3/effect/JSONSchema" },
			{ name: "KeyedPool", href: "/docs/api/v3/effect/KeyedPool" },
			{ name: "Layer", href: "/docs/api/v3/effect/Layer" },
			{ name: "LayerMap", href: "/docs/api/v3/effect/LayerMap" },
			{ name: "List", href: "/docs/api/v3/effect/List" },
			{ name: "Logger", href: "/docs/api/v3/effect/Logger" },
			{ name: "LogLevel", href: "/docs/api/v3/effect/LogLevel" },
			{ name: "LogSpan", href: "/docs/api/v3/effect/LogSpan" },
			{ name: "Mailbox", href: "/docs/api/v3/effect/Mailbox" },
			{ name: "ManagedRuntime", href: "/docs/api/v3/effect/ManagedRuntime" },
			{ name: "Match", href: "/docs/api/v3/effect/Match" },
			{ name: "MergeDecision", href: "/docs/api/v3/effect/MergeDecision" },
			{ name: "MergeState", href: "/docs/api/v3/effect/MergeState" },
			{ name: "MergeStrategy", href: "/docs/api/v3/effect/MergeStrategy" },
			{ name: "Metric", href: "/docs/api/v3/effect/Metric" },
			{
				name: "MetricBoundaries",
				href: "/docs/api/v3/effect/MetricBoundaries",
			},
			{ name: "MetricHook", href: "/docs/api/v3/effect/MetricHook" },
			{ name: "MetricKey", href: "/docs/api/v3/effect/MetricKey" },
			{ name: "MetricKeyType", href: "/docs/api/v3/effect/MetricKeyType" },
			{ name: "MetricLabel", href: "/docs/api/v3/effect/MetricLabel" },
			{ name: "MetricPair", href: "/docs/api/v3/effect/MetricPair" },
			{ name: "MetricPolling", href: "/docs/api/v3/effect/MetricPolling" },
			{ name: "MetricRegistry", href: "/docs/api/v3/effect/MetricRegistry" },
			{ name: "MetricState", href: "/docs/api/v3/effect/MetricState" },
			{ name: "Micro", href: "/docs/api/v3/effect/Micro" },
			{ name: "ModuleVersion", href: "/docs/api/v3/effect/ModuleVersion" },
			{ name: "MutableHashMap", href: "/docs/api/v3/effect/MutableHashMap" },
			{ name: "MutableHashSet", href: "/docs/api/v3/effect/MutableHashSet" },
			{ name: "MutableList", href: "/docs/api/v3/effect/MutableList" },
			{ name: "MutableQueue", href: "/docs/api/v3/effect/MutableQueue" },
			{ name: "MutableRef", href: "/docs/api/v3/effect/MutableRef" },
			{
				name: "NonEmptyIterable",
				href: "/docs/api/v3/effect/NonEmptyIterable",
			},
			{ name: "Number", href: "/docs/api/v3/effect/Number" },
			{ name: "Option", href: "/docs/api/v3/effect/Option" },
			{ name: "Order", href: "/docs/api/v3/effect/Order" },
			{ name: "Ordering", href: "/docs/api/v3/effect/Ordering" },
			{ name: "ParseResult", href: "/docs/api/v3/effect/ParseResult" },
			{
				name: "PartitionedSemaphore",
				href: "/docs/api/v3/effect/PartitionedSemaphore",
			},
			{ name: "Pipeable", href: "/docs/api/v3/effect/Pipeable" },
			{ name: "Pool", href: "/docs/api/v3/effect/Pool" },
			{ name: "Predicate", href: "/docs/api/v3/effect/Predicate" },
			{ name: "Pretty", href: "/docs/api/v3/effect/Pretty" },
			{ name: "PrimaryKey", href: "/docs/api/v3/effect/PrimaryKey" },
			{ name: "PubSub", href: "/docs/api/v3/effect/PubSub" },
			{ name: "Queue", href: "/docs/api/v3/effect/Queue" },
			{ name: "Random", href: "/docs/api/v3/effect/Random" },
			{ name: "RateLimiter", href: "/docs/api/v3/effect/RateLimiter" },
			{ name: "RcMap", href: "/docs/api/v3/effect/RcMap" },
			{ name: "RcRef", href: "/docs/api/v3/effect/RcRef" },
			{ name: "Readable", href: "/docs/api/v3/effect/Readable" },
			{ name: "Record", href: "/docs/api/v3/effect/Record" },
			{ name: "Redacted", href: "/docs/api/v3/effect/Redacted" },
			{ name: "RedBlackTree", href: "/docs/api/v3/effect/RedBlackTree" },
			{ name: "Ref", href: "/docs/api/v3/effect/Ref" },
			{ name: "RegExp", href: "/docs/api/v3/effect/RegExp" },
			{ name: "Reloadable", href: "/docs/api/v3/effect/Reloadable" },
			{ name: "Request", href: "/docs/api/v3/effect/Request" },
			{ name: "RequestBlock", href: "/docs/api/v3/effect/RequestBlock" },
			{ name: "RequestResolver", href: "/docs/api/v3/effect/RequestResolver" },
			{ name: "Resource", href: "/docs/api/v3/effect/Resource" },
			{ name: "Runtime", href: "/docs/api/v3/effect/Runtime" },
			{ name: "RuntimeFlags", href: "/docs/api/v3/effect/RuntimeFlags" },
			{
				name: "RuntimeFlagsPatch",
				href: "/docs/api/v3/effect/RuntimeFlagsPatch",
			},
			{ name: "Schedule", href: "/docs/api/v3/effect/Schedule" },
			{
				name: "ScheduleDecision",
				href: "/docs/api/v3/effect/ScheduleDecision",
			},
			{
				name: "ScheduleInterval",
				href: "/docs/api/v3/effect/ScheduleInterval",
			},
			{
				name: "ScheduleIntervals",
				href: "/docs/api/v3/effect/ScheduleIntervals",
			},
			{ name: "Scheduler", href: "/docs/api/v3/effect/Scheduler" },
			{ name: "Schema", href: "/docs/api/v3/effect/Schema" },
			{ name: "SchemaAST", href: "/docs/api/v3/effect/SchemaAST" },
			{ name: "Scope", href: "/docs/api/v3/effect/Scope" },
			{ name: "ScopedCache", href: "/docs/api/v3/effect/ScopedCache" },
			{ name: "ScopedRef", href: "/docs/api/v3/effect/ScopedRef" },
			{ name: "Secret", href: "/docs/api/v3/effect/Secret" },
			{
				name: "SingleProducerAsyncInput",
				href: "/docs/api/v3/effect/SingleProducerAsyncInput",
			},
			{ name: "Sink", href: "/docs/api/v3/effect/Sink" },
			{ name: "SortedMap", href: "/docs/api/v3/effect/SortedMap" },
			{ name: "SortedSet", href: "/docs/api/v3/effect/SortedSet" },
			{ name: "STM", href: "/docs/api/v3/effect/STM" },
			{ name: "Stream", href: "/docs/api/v3/effect/Stream" },
			{ name: "Streamable", href: "/docs/api/v3/effect/Streamable" },
			{ name: "StreamEmit", href: "/docs/api/v3/effect/StreamEmit" },
			{
				name: "StreamHaltStrategy",
				href: "/docs/api/v3/effect/StreamHaltStrategy",
			},
			{ name: "String", href: "/docs/api/v3/effect/String" },
			{ name: "Struct", href: "/docs/api/v3/effect/Struct" },
			{ name: "Subscribable", href: "/docs/api/v3/effect/Subscribable" },
			{ name: "SubscriptionRef", href: "/docs/api/v3/effect/SubscriptionRef" },
			{ name: "Supervisor", href: "/docs/api/v3/effect/Supervisor" },
			{ name: "Symbol", href: "/docs/api/v3/effect/Symbol" },
			{ name: "SynchronizedRef", href: "/docs/api/v3/effect/SynchronizedRef" },
			{ name: "Take", href: "/docs/api/v3/effect/Take" },
			{ name: "TArray", href: "/docs/api/v3/effect/TArray" },
			{ name: "TDeferred", href: "/docs/api/v3/effect/TDeferred" },
			{ name: "TestAnnotation", href: "/docs/api/v3/effect/TestAnnotation" },
			{
				name: "TestAnnotationMap",
				href: "/docs/api/v3/effect/TestAnnotationMap",
			},
			{ name: "TestAnnotations", href: "/docs/api/v3/effect/TestAnnotations" },
			{ name: "TestClock", href: "/docs/api/v3/effect/TestClock" },
			{ name: "TestConfig", href: "/docs/api/v3/effect/TestConfig" },
			{ name: "TestContext", href: "/docs/api/v3/effect/TestContext" },
			{ name: "TestLive", href: "/docs/api/v3/effect/TestLive" },
			{ name: "TestServices", href: "/docs/api/v3/effect/TestServices" },
			{ name: "TestSized", href: "/docs/api/v3/effect/TestSized" },
			{ name: "TMap", href: "/docs/api/v3/effect/TMap" },
			{ name: "TPriorityQueue", href: "/docs/api/v3/effect/TPriorityQueue" },
			{ name: "TPubSub", href: "/docs/api/v3/effect/TPubSub" },
			{ name: "TQueue", href: "/docs/api/v3/effect/TQueue" },
			{ name: "Tracer", href: "/docs/api/v3/effect/Tracer" },
			{ name: "TRandom", href: "/docs/api/v3/effect/TRandom" },
			{ name: "TReentrantLock", href: "/docs/api/v3/effect/TReentrantLock" },
			{ name: "TRef", href: "/docs/api/v3/effect/TRef" },
			{ name: "Trie", href: "/docs/api/v3/effect/Trie" },
			{ name: "TSemaphore", href: "/docs/api/v3/effect/TSemaphore" },
			{ name: "TSet", href: "/docs/api/v3/effect/TSet" },
			{
				name: "TSubscriptionRef",
				href: "/docs/api/v3/effect/TSubscriptionRef",
			},
			{ name: "Tuple", href: "/docs/api/v3/effect/Tuple" },
			{ name: "Types", href: "/docs/api/v3/effect/Types" },
			{ name: "Unify", href: "/docs/api/v3/effect/Unify" },
			{
				name: "UpstreamPullRequest",
				href: "/docs/api/v3/effect/UpstreamPullRequest",
			},
			{
				name: "UpstreamPullStrategy",
				href: "/docs/api/v3/effect/UpstreamPullStrategy",
			},
			{ name: "Utils", href: "/docs/api/v3/effect/Utils" },
		],
	},
	{
		slug: "experimental",
		name: "@effect/experimental",
		description:
			"Experimental modules under active development \u2014 APIs may change without notice.",
		modules: [
			{ name: "DevTools", href: "/docs/api/v3/experimental/DevTools" },
			{
				name: "DevTools/Client",
				href: "/docs/api/v3/experimental/DevTools/Client",
			},
			{
				name: "DevTools/Domain",
				href: "/docs/api/v3/experimental/DevTools/Domain",
			},
			{
				name: "DevTools/Server",
				href: "/docs/api/v3/experimental/DevTools/Server",
			},
			{ name: "Event", href: "/docs/api/v3/experimental/Event" },
			{ name: "EventGroup", href: "/docs/api/v3/experimental/EventGroup" },
			{ name: "EventJournal", href: "/docs/api/v3/experimental/EventJournal" },
			{ name: "EventLog", href: "/docs/api/v3/experimental/EventLog" },
			{
				name: "EventLogEncryption",
				href: "/docs/api/v3/experimental/EventLogEncryption",
			},
			{
				name: "EventLogRemote",
				href: "/docs/api/v3/experimental/EventLogRemote",
			},
			{
				name: "EventLogServer",
				href: "/docs/api/v3/experimental/EventLogServer",
			},
			{
				name: "EventLogServer/Cloudflare",
				href: "/docs/api/v3/experimental/EventLogServer/Cloudflare",
			},
			{ name: "index", href: "/docs/api/v3/experimental/index" },
			{ name: "Machine", href: "/docs/api/v3/experimental/Machine" },
			{
				name: "Machine/Procedure",
				href: "/docs/api/v3/experimental/Machine/Procedure",
			},
			{
				name: "Machine/ProcedureList",
				href: "/docs/api/v3/experimental/Machine/ProcedureList",
			},
			{
				name: "Machine/SerializableProcedureList",
				href: "/docs/api/v3/experimental/Machine/SerializableProcedureList",
			},
			{
				name: "PersistedCache",
				href: "/docs/api/v3/experimental/PersistedCache",
			},
			{
				name: "PersistedQueue",
				href: "/docs/api/v3/experimental/PersistedQueue",
			},
			{
				name: "PersistedQueue/Redis",
				href: "/docs/api/v3/experimental/PersistedQueue/Redis",
			},
			{ name: "Persistence", href: "/docs/api/v3/experimental/Persistence" },
			{
				name: "Persistence/Lmdb",
				href: "/docs/api/v3/experimental/Persistence/Lmdb",
			},
			{
				name: "Persistence/Redis",
				href: "/docs/api/v3/experimental/Persistence/Redis",
			},
			{ name: "RateLimiter", href: "/docs/api/v3/experimental/RateLimiter" },
			{
				name: "RateLimiter/Redis",
				href: "/docs/api/v3/experimental/RateLimiter/Redis",
			},
			{ name: "Reactivity", href: "/docs/api/v3/experimental/Reactivity" },
			{
				name: "RequestResolver",
				href: "/docs/api/v3/experimental/RequestResolver",
			},
			{ name: "Sse", href: "/docs/api/v3/experimental/Sse" },
			{
				name: "VariantSchema",
				href: "/docs/api/v3/experimental/VariantSchema",
			},
		],
	},
	{
		slug: "opentelemetry",
		name: "@effect/opentelemetry",
		description: "OpenTelemetry integration for tracing, metrics, and logging.",
		modules: [
			{ name: "index", href: "/docs/api/v3/opentelemetry/index" },
			{ name: "Logger", href: "/docs/api/v3/opentelemetry/Logger" },
			{ name: "Metrics", href: "/docs/api/v3/opentelemetry/Metrics" },
			{ name: "NodeSdk", href: "/docs/api/v3/opentelemetry/NodeSdk" },
			{ name: "Otlp", href: "/docs/api/v3/opentelemetry/Otlp" },
			{ name: "OtlpLogger", href: "/docs/api/v3/opentelemetry/OtlpLogger" },
			{ name: "OtlpMetrics", href: "/docs/api/v3/opentelemetry/OtlpMetrics" },
			{ name: "OtlpResource", href: "/docs/api/v3/opentelemetry/OtlpResource" },
			{
				name: "OtlpSerialization",
				href: "/docs/api/v3/opentelemetry/OtlpSerialization",
			},
			{ name: "OtlpTracer", href: "/docs/api/v3/opentelemetry/OtlpTracer" },
			{ name: "Resource", href: "/docs/api/v3/opentelemetry/Resource" },
			{ name: "Tracer", href: "/docs/api/v3/opentelemetry/Tracer" },
			{ name: "WebSdk", href: "/docs/api/v3/opentelemetry/WebSdk" },
		],
	},
	{
		slug: "platform",
		name: "@effect/platform",
		description:
			"Platform-agnostic abstractions for HTTP, file systems, sockets, workers, and more.",
		modules: [
			{ name: "ChannelSchema", href: "/docs/api/v3/platform/ChannelSchema" },
			{ name: "Command", href: "/docs/api/v3/platform/Command" },
			{
				name: "CommandExecutor",
				href: "/docs/api/v3/platform/CommandExecutor",
			},
			{ name: "Cookies", href: "/docs/api/v3/platform/Cookies" },
			{ name: "Effectify", href: "/docs/api/v3/platform/Effectify" },
			{ name: "Error", href: "/docs/api/v3/platform/Error" },
			{ name: "Etag", href: "/docs/api/v3/platform/Etag" },
			{
				name: "FetchHttpClient",
				href: "/docs/api/v3/platform/FetchHttpClient",
			},
			{ name: "FileSystem", href: "/docs/api/v3/platform/FileSystem" },
			{ name: "Headers", href: "/docs/api/v3/platform/Headers" },
			{ name: "HttpApi", href: "/docs/api/v3/platform/HttpApi" },
			{ name: "HttpApiBuilder", href: "/docs/api/v3/platform/HttpApiBuilder" },
			{ name: "HttpApiClient", href: "/docs/api/v3/platform/HttpApiClient" },
			{
				name: "HttpApiEndpoint",
				href: "/docs/api/v3/platform/HttpApiEndpoint",
			},
			{ name: "HttpApiError", href: "/docs/api/v3/platform/HttpApiError" },
			{ name: "HttpApiGroup", href: "/docs/api/v3/platform/HttpApiGroup" },
			{
				name: "HttpApiMiddleware",
				href: "/docs/api/v3/platform/HttpApiMiddleware",
			},
			{ name: "HttpApiScalar", href: "/docs/api/v3/platform/HttpApiScalar" },
			{ name: "HttpApiSchema", href: "/docs/api/v3/platform/HttpApiSchema" },
			{
				name: "HttpApiSecurity",
				href: "/docs/api/v3/platform/HttpApiSecurity",
			},
			{ name: "HttpApiSwagger", href: "/docs/api/v3/platform/HttpApiSwagger" },
			{ name: "HttpApp", href: "/docs/api/v3/platform/HttpApp" },
			{ name: "HttpBody", href: "/docs/api/v3/platform/HttpBody" },
			{ name: "HttpClient", href: "/docs/api/v3/platform/HttpClient" },
			{
				name: "HttpClientError",
				href: "/docs/api/v3/platform/HttpClientError",
			},
			{
				name: "HttpClientRequest",
				href: "/docs/api/v3/platform/HttpClientRequest",
			},
			{
				name: "HttpClientResponse",
				href: "/docs/api/v3/platform/HttpClientResponse",
			},
			{
				name: "HttpIncomingMessage",
				href: "/docs/api/v3/platform/HttpIncomingMessage",
			},
			{
				name: "HttpLayerRouter",
				href: "/docs/api/v3/platform/HttpLayerRouter",
			},
			{ name: "HttpMethod", href: "/docs/api/v3/platform/HttpMethod" },
			{ name: "HttpMiddleware", href: "/docs/api/v3/platform/HttpMiddleware" },
			{ name: "HttpMultiplex", href: "/docs/api/v3/platform/HttpMultiplex" },
			{ name: "HttpPlatform", href: "/docs/api/v3/platform/HttpPlatform" },
			{ name: "HttpRouter", href: "/docs/api/v3/platform/HttpRouter" },
			{ name: "HttpServer", href: "/docs/api/v3/platform/HttpServer" },
			{
				name: "HttpServerError",
				href: "/docs/api/v3/platform/HttpServerError",
			},
			{
				name: "HttpServerRequest",
				href: "/docs/api/v3/platform/HttpServerRequest",
			},
			{
				name: "HttpServerRespondable",
				href: "/docs/api/v3/platform/HttpServerRespondable",
			},
			{
				name: "HttpServerResponse",
				href: "/docs/api/v3/platform/HttpServerResponse",
			},
			{
				name: "HttpTraceContext",
				href: "/docs/api/v3/platform/HttpTraceContext",
			},
			{ name: "index", href: "/docs/api/v3/platform/index" },
			{ name: "KeyValueStore", href: "/docs/api/v3/platform/KeyValueStore" },
			{ name: "MsgPack", href: "/docs/api/v3/platform/MsgPack" },
			{ name: "Multipart", href: "/docs/api/v3/platform/Multipart" },
			{ name: "Ndjson", href: "/docs/api/v3/platform/Ndjson" },
			{ name: "OpenApi", href: "/docs/api/v3/platform/OpenApi" },
			{
				name: "OpenApiJsonSchema",
				href: "/docs/api/v3/platform/OpenApiJsonSchema",
			},
			{ name: "Path", href: "/docs/api/v3/platform/Path" },
			{
				name: "PlatformConfigProvider",
				href: "/docs/api/v3/platform/PlatformConfigProvider",
			},
			{ name: "PlatformLogger", href: "/docs/api/v3/platform/PlatformLogger" },
			{ name: "Runtime", href: "/docs/api/v3/platform/Runtime" },
			{ name: "Socket", href: "/docs/api/v3/platform/Socket" },
			{ name: "SocketServer", href: "/docs/api/v3/platform/SocketServer" },
			{ name: "Template", href: "/docs/api/v3/platform/Template" },
			{ name: "Terminal", href: "/docs/api/v3/platform/Terminal" },
			{ name: "Transferable", href: "/docs/api/v3/platform/Transferable" },
			{ name: "Url", href: "/docs/api/v3/platform/Url" },
			{ name: "UrlParams", href: "/docs/api/v3/platform/UrlParams" },
			{ name: "Worker", href: "/docs/api/v3/platform/Worker" },
			{ name: "WorkerError", href: "/docs/api/v3/platform/WorkerError" },
			{ name: "WorkerRunner", href: "/docs/api/v3/platform/WorkerRunner" },
		],
	},
	{
		slug: "platform-browser",
		name: "@effect/platform-browser",
		description: "Browser implementations of the platform abstractions.",
		modules: [
			{
				name: "BrowserHttpClient",
				href: "/docs/api/v3/platform-browser/BrowserHttpClient",
			},
			{
				name: "BrowserKeyValueStore",
				href: "/docs/api/v3/platform-browser/BrowserKeyValueStore",
			},
			{
				name: "BrowserRuntime",
				href: "/docs/api/v3/platform-browser/BrowserRuntime",
			},
			{
				name: "BrowserSocket",
				href: "/docs/api/v3/platform-browser/BrowserSocket",
			},
			{
				name: "BrowserStream",
				href: "/docs/api/v3/platform-browser/BrowserStream",
			},
			{
				name: "BrowserWorker",
				href: "/docs/api/v3/platform-browser/BrowserWorker",
			},
			{
				name: "BrowserWorkerRunner",
				href: "/docs/api/v3/platform-browser/BrowserWorkerRunner",
			},
			{ name: "Clipboard", href: "/docs/api/v3/platform-browser/Clipboard" },
			{
				name: "Geolocation",
				href: "/docs/api/v3/platform-browser/Geolocation",
			},
			{ name: "index", href: "/docs/api/v3/platform-browser/index" },
			{
				name: "Permissions",
				href: "/docs/api/v3/platform-browser/Permissions",
			},
		],
	},
	{
		slug: "platform-bun",
		name: "@effect/platform-bun",
		description: "Bun implementations of the platform abstractions.",
		modules: [
			{
				name: "BunClusterHttp",
				href: "/docs/api/v3/platform-bun/BunClusterHttp",
			},
			{
				name: "BunClusterSocket",
				href: "/docs/api/v3/platform-bun/BunClusterSocket",
			},
			{
				name: "BunCommandExecutor",
				href: "/docs/api/v3/platform-bun/BunCommandExecutor",
			},
			{ name: "BunContext", href: "/docs/api/v3/platform-bun/BunContext" },
			{
				name: "BunFileSystem",
				href: "/docs/api/v3/platform-bun/BunFileSystem",
			},
			{
				name: "BunFileSystem/ParcelWatcher",
				href: "/docs/api/v3/platform-bun/BunFileSystem/ParcelWatcher",
			},
			{
				name: "BunHttpPlatform",
				href: "/docs/api/v3/platform-bun/BunHttpPlatform",
			},
			{
				name: "BunHttpServer",
				href: "/docs/api/v3/platform-bun/BunHttpServer",
			},
			{
				name: "BunHttpServerRequest",
				href: "/docs/api/v3/platform-bun/BunHttpServerRequest",
			},
			{
				name: "BunKeyValueStore",
				href: "/docs/api/v3/platform-bun/BunKeyValueStore",
			},
			{ name: "BunMultipart", href: "/docs/api/v3/platform-bun/BunMultipart" },
			{ name: "BunPath", href: "/docs/api/v3/platform-bun/BunPath" },
			{ name: "BunRuntime", href: "/docs/api/v3/platform-bun/BunRuntime" },
			{ name: "BunSink", href: "/docs/api/v3/platform-bun/BunSink" },
			{ name: "BunSocket", href: "/docs/api/v3/platform-bun/BunSocket" },
			{
				name: "BunSocketServer",
				href: "/docs/api/v3/platform-bun/BunSocketServer",
			},
			{ name: "BunStream", href: "/docs/api/v3/platform-bun/BunStream" },
			{ name: "BunTerminal", href: "/docs/api/v3/platform-bun/BunTerminal" },
			{ name: "BunWorker", href: "/docs/api/v3/platform-bun/BunWorker" },
			{
				name: "BunWorkerRunner",
				href: "/docs/api/v3/platform-bun/BunWorkerRunner",
			},
			{ name: "index", href: "/docs/api/v3/platform-bun/index" },
		],
	},
	{
		slug: "platform-node",
		name: "@effect/platform-node",
		description: "Node.js implementations of the platform abstractions.",
		modules: [
			{ name: "index", href: "/docs/api/v3/platform-node/index" },
			{
				name: "NodeClusterHttp",
				href: "/docs/api/v3/platform-node/NodeClusterHttp",
			},
			{
				name: "NodeClusterSocket",
				href: "/docs/api/v3/platform-node/NodeClusterSocket",
			},
			{
				name: "NodeCommandExecutor",
				href: "/docs/api/v3/platform-node/NodeCommandExecutor",
			},
			{ name: "NodeContext", href: "/docs/api/v3/platform-node/NodeContext" },
			{
				name: "NodeFileSystem",
				href: "/docs/api/v3/platform-node/NodeFileSystem",
			},
			{
				name: "NodeFileSystem/ParcelWatcher",
				href: "/docs/api/v3/platform-node/NodeFileSystem/ParcelWatcher",
			},
			{
				name: "NodeHttpClient",
				href: "/docs/api/v3/platform-node/NodeHttpClient",
			},
			{
				name: "NodeHttpPlatform",
				href: "/docs/api/v3/platform-node/NodeHttpPlatform",
			},
			{
				name: "NodeHttpServer",
				href: "/docs/api/v3/platform-node/NodeHttpServer",
			},
			{
				name: "NodeHttpServerRequest",
				href: "/docs/api/v3/platform-node/NodeHttpServerRequest",
			},
			{
				name: "NodeKeyValueStore",
				href: "/docs/api/v3/platform-node/NodeKeyValueStore",
			},
			{
				name: "NodeMultipart",
				href: "/docs/api/v3/platform-node/NodeMultipart",
			},
			{ name: "NodePath", href: "/docs/api/v3/platform-node/NodePath" },
			{ name: "NodeRuntime", href: "/docs/api/v3/platform-node/NodeRuntime" },
			{ name: "NodeSink", href: "/docs/api/v3/platform-node/NodeSink" },
			{ name: "NodeSocket", href: "/docs/api/v3/platform-node/NodeSocket" },
			{
				name: "NodeSocketServer",
				href: "/docs/api/v3/platform-node/NodeSocketServer",
			},
			{ name: "NodeStream", href: "/docs/api/v3/platform-node/NodeStream" },
			{ name: "NodeTerminal", href: "/docs/api/v3/platform-node/NodeTerminal" },
			{ name: "NodeWorker", href: "/docs/api/v3/platform-node/NodeWorker" },
			{
				name: "NodeWorkerRunner",
				href: "/docs/api/v3/platform-node/NodeWorkerRunner",
			},
			{ name: "Undici", href: "/docs/api/v3/platform-node/Undici" },
		],
	},
	{
		slug: "platform-node-shared",
		name: "@effect/platform-node-shared",
		description:
			"Shared internals for Node.js-compatible platform implementations.",
		modules: [
			{
				name: "NodeClusterSocket",
				href: "/docs/api/v3/platform-node-shared/NodeClusterSocket",
			},
			{
				name: "NodeCommandExecutor",
				href: "/docs/api/v3/platform-node-shared/NodeCommandExecutor",
			},
			{
				name: "NodeFileSystem",
				href: "/docs/api/v3/platform-node-shared/NodeFileSystem",
			},
			{
				name: "NodeFileSystem/ParcelWatcher",
				href: "/docs/api/v3/platform-node-shared/NodeFileSystem/ParcelWatcher",
			},
			{
				name: "NodeKeyValueStore",
				href: "/docs/api/v3/platform-node-shared/NodeKeyValueStore",
			},
			{
				name: "NodeMultipart",
				href: "/docs/api/v3/platform-node-shared/NodeMultipart",
			},
			{ name: "NodePath", href: "/docs/api/v3/platform-node-shared/NodePath" },
			{
				name: "NodeRuntime",
				href: "/docs/api/v3/platform-node-shared/NodeRuntime",
			},
			{ name: "NodeSink", href: "/docs/api/v3/platform-node-shared/NodeSink" },
			{
				name: "NodeSocket",
				href: "/docs/api/v3/platform-node-shared/NodeSocket",
			},
			{
				name: "NodeSocketServer",
				href: "/docs/api/v3/platform-node-shared/NodeSocketServer",
			},
			{
				name: "NodeStream",
				href: "/docs/api/v3/platform-node-shared/NodeStream",
			},
			{
				name: "NodeTerminal",
				href: "/docs/api/v3/platform-node-shared/NodeTerminal",
			},
		],
	},
	{
		slug: "printer",
		name: "@effect/printer",
		description: "A pretty-printer for rendering structured documents to text.",
		modules: [
			{ name: "Doc", href: "/docs/api/v3/printer/Doc" },
			{ name: "DocStream", href: "/docs/api/v3/printer/DocStream" },
			{ name: "DocTree", href: "/docs/api/v3/printer/DocTree" },
			{ name: "Flatten", href: "/docs/api/v3/printer/Flatten" },
			{ name: "index", href: "/docs/api/v3/printer/index" },
			{ name: "Layout", href: "/docs/api/v3/printer/Layout" },
			{ name: "Optimize", href: "/docs/api/v3/printer/Optimize" },
			{ name: "PageWidth", href: "/docs/api/v3/printer/PageWidth" },
		],
	},
	{
		slug: "printer-ansi",
		name: "@effect/printer-ansi",
		description:
			"ANSI terminal rendering with colors and styles for the printer.",
		modules: [
			{ name: "Ansi", href: "/docs/api/v3/printer-ansi/Ansi" },
			{ name: "AnsiDoc", href: "/docs/api/v3/printer-ansi/AnsiDoc" },
			{ name: "Color", href: "/docs/api/v3/printer-ansi/Color" },
			{ name: "index", href: "/docs/api/v3/printer-ansi/index" },
		],
	},
	{
		slug: "rpc",
		name: "@effect/rpc",
		description: "Type-safe remote procedure calls between client and server.",
		modules: [
			{ name: "index", href: "/docs/api/v3/rpc/index" },
			{ name: "Rpc", href: "/docs/api/v3/rpc/Rpc" },
			{ name: "RpcClient", href: "/docs/api/v3/rpc/RpcClient" },
			{ name: "RpcClientError", href: "/docs/api/v3/rpc/RpcClientError" },
			{ name: "RpcGroup", href: "/docs/api/v3/rpc/RpcGroup" },
			{ name: "RpcMessage", href: "/docs/api/v3/rpc/RpcMessage" },
			{ name: "RpcMiddleware", href: "/docs/api/v3/rpc/RpcMiddleware" },
			{ name: "RpcSchema", href: "/docs/api/v3/rpc/RpcSchema" },
			{ name: "RpcSerialization", href: "/docs/api/v3/rpc/RpcSerialization" },
			{ name: "RpcServer", href: "/docs/api/v3/rpc/RpcServer" },
			{ name: "RpcTest", href: "/docs/api/v3/rpc/RpcTest" },
			{ name: "RpcWorker", href: "/docs/api/v3/rpc/RpcWorker" },
		],
	},
	{
		slug: "sql",
		name: "@effect/sql",
		description:
			"SQL toolkit with clients, statements, migrations, models, and resolvers.",
		modules: [
			{ name: "index", href: "/docs/api/v3/sql/index" },
			{ name: "Migrator", href: "/docs/api/v3/sql/Migrator" },
			{
				name: "Migrator/FileSystem",
				href: "/docs/api/v3/sql/Migrator/FileSystem",
			},
			{ name: "Model", href: "/docs/api/v3/sql/Model" },
			{ name: "SqlClient", href: "/docs/api/v3/sql/SqlClient" },
			{ name: "SqlConnection", href: "/docs/api/v3/sql/SqlConnection" },
			{ name: "SqlError", href: "/docs/api/v3/sql/SqlError" },
			{ name: "SqlEventJournal", href: "/docs/api/v3/sql/SqlEventJournal" },
			{ name: "SqlEventLogServer", href: "/docs/api/v3/sql/SqlEventLogServer" },
			{ name: "SqlPersistedQueue", href: "/docs/api/v3/sql/SqlPersistedQueue" },
			{ name: "SqlResolver", href: "/docs/api/v3/sql/SqlResolver" },
			{ name: "SqlSchema", href: "/docs/api/v3/sql/SqlSchema" },
			{ name: "SqlStream", href: "/docs/api/v3/sql/SqlStream" },
			{ name: "Statement", href: "/docs/api/v3/sql/Statement" },
		],
	},
	{
		slug: "sql-clickhouse",
		name: "@effect/sql-clickhouse",
		description: "ClickHouse client and migrator.",
		modules: [
			{
				name: "ClickhouseClient",
				href: "/docs/api/v3/sql-clickhouse/ClickhouseClient",
			},
			{
				name: "ClickhouseMigrator",
				href: "/docs/api/v3/sql-clickhouse/ClickhouseMigrator",
			},
			{ name: "index", href: "/docs/api/v3/sql-clickhouse/index" },
		],
	},
	{
		slug: "sql-d1",
		name: "@effect/sql-d1",
		description: "Cloudflare D1 client.",
		modules: [
			{ name: "D1Client", href: "/docs/api/v3/sql-d1/D1Client" },
			{ name: "index", href: "/docs/api/v3/sql-d1/index" },
		],
	},
	{
		slug: "sql-drizzle",
		name: "@effect/sql-drizzle",
		description: "Drizzle ORM integration for Postgres, MySQL, and SQLite.",
		modules: [
			{ name: "Mysql", href: "/docs/api/v3/sql-drizzle/Mysql" },
			{ name: "Pg", href: "/docs/api/v3/sql-drizzle/Pg" },
			{ name: "Sqlite", href: "/docs/api/v3/sql-drizzle/Sqlite" },
		],
	},
	{
		slug: "sql-kysely",
		name: "@effect/sql-kysely",
		description:
			"Kysely query-builder integration for Postgres, MySQL, MSSQL, and SQLite.",
		modules: [
			{ name: "Kysely", href: "/docs/api/v3/sql-kysely/Kysely" },
			{ name: "Mssql", href: "/docs/api/v3/sql-kysely/Mssql" },
			{ name: "Mysql", href: "/docs/api/v3/sql-kysely/Mysql" },
			{ name: "patch.types", href: "/docs/api/v3/sql-kysely/patch.types" },
			{ name: "Pg", href: "/docs/api/v3/sql-kysely/Pg" },
			{ name: "Sqlite", href: "/docs/api/v3/sql-kysely/Sqlite" },
		],
	},
	{
		slug: "sql-libsql",
		name: "@effect/sql-libsql",
		description: "libSQL client and migrator.",
		modules: [
			{ name: "index", href: "/docs/api/v3/sql-libsql/index" },
			{ name: "LibsqlClient", href: "/docs/api/v3/sql-libsql/LibsqlClient" },
			{
				name: "LibsqlMigrator",
				href: "/docs/api/v3/sql-libsql/LibsqlMigrator",
			},
		],
	},
	{
		slug: "sql-mssql",
		name: "@effect/sql-mssql",
		description: "Microsoft SQL Server client and migrator.",
		modules: [
			{ name: "index", href: "/docs/api/v3/sql-mssql/index" },
			{ name: "MssqlClient", href: "/docs/api/v3/sql-mssql/MssqlClient" },
			{ name: "MssqlMigrator", href: "/docs/api/v3/sql-mssql/MssqlMigrator" },
			{ name: "Parameter", href: "/docs/api/v3/sql-mssql/Parameter" },
			{ name: "Procedure", href: "/docs/api/v3/sql-mssql/Procedure" },
		],
	},
	{
		slug: "sql-mysql2",
		name: "@effect/sql-mysql2",
		description: "MySQL client and migrator built on mysql2.",
		modules: [
			{ name: "index", href: "/docs/api/v3/sql-mysql2/index" },
			{ name: "MysqlClient", href: "/docs/api/v3/sql-mysql2/MysqlClient" },
			{ name: "MysqlMigrator", href: "/docs/api/v3/sql-mysql2/MysqlMigrator" },
		],
	},
	{
		slug: "sql-pg",
		name: "@effect/sql-pg",
		description: "PostgreSQL client and migrator.",
		modules: [
			{ name: "index", href: "/docs/api/v3/sql-pg/index" },
			{ name: "PgClient", href: "/docs/api/v3/sql-pg/PgClient" },
			{ name: "PgMigrator", href: "/docs/api/v3/sql-pg/PgMigrator" },
		],
	},
	{
		slug: "sql-sqlite-bun",
		name: "@effect/sql-sqlite-bun",
		description: "SQLite client and migrator for Bun.",
		modules: [
			{ name: "index", href: "/docs/api/v3/sql-sqlite-bun/index" },
			{
				name: "SqliteClient",
				href: "/docs/api/v3/sql-sqlite-bun/SqliteClient",
			},
			{
				name: "SqliteMigrator",
				href: "/docs/api/v3/sql-sqlite-bun/SqliteMigrator",
			},
		],
	},
	{
		slug: "sql-sqlite-do",
		name: "@effect/sql-sqlite-do",
		description: "SQLite client and migrator for Cloudflare Durable Objects.",
		modules: [
			{ name: "index", href: "/docs/api/v3/sql-sqlite-do/index" },
			{ name: "SqliteClient", href: "/docs/api/v3/sql-sqlite-do/SqliteClient" },
			{
				name: "SqliteMigrator",
				href: "/docs/api/v3/sql-sqlite-do/SqliteMigrator",
			},
		],
	},
	{
		slug: "sql-sqlite-node",
		name: "@effect/sql-sqlite-node",
		description: "SQLite client and migrator for Node.js.",
		modules: [
			{ name: "index", href: "/docs/api/v3/sql-sqlite-node/index" },
			{
				name: "SqliteClient",
				href: "/docs/api/v3/sql-sqlite-node/SqliteClient",
			},
			{
				name: "SqliteMigrator",
				href: "/docs/api/v3/sql-sqlite-node/SqliteMigrator",
			},
		],
	},
	{
		slug: "sql-sqlite-react-native",
		name: "@effect/sql-sqlite-react-native",
		description: "SQLite client and migrator for React Native.",
		modules: [
			{ name: "index", href: "/docs/api/v3/sql-sqlite-react-native/index" },
			{
				name: "SqliteClient",
				href: "/docs/api/v3/sql-sqlite-react-native/SqliteClient",
			},
			{
				name: "SqliteMigrator",
				href: "/docs/api/v3/sql-sqlite-react-native/SqliteMigrator",
			},
		],
	},
	{
		slug: "sql-sqlite-wasm",
		name: "@effect/sql-sqlite-wasm",
		description: "SQLite client and migrator running on WebAssembly (OPFS).",
		modules: [
			{ name: "index", href: "/docs/api/v3/sql-sqlite-wasm/index" },
			{ name: "OpfsWorker", href: "/docs/api/v3/sql-sqlite-wasm/OpfsWorker" },
			{ name: "sqlite-wasm", href: "/docs/api/v3/sql-sqlite-wasm/sqlite-wasm" },
			{
				name: "SqliteClient",
				href: "/docs/api/v3/sql-sqlite-wasm/SqliteClient",
			},
			{
				name: "SqliteMigrator",
				href: "/docs/api/v3/sql-sqlite-wasm/SqliteMigrator",
			},
		],
	},
	{
		slug: "typeclass",
		name: "@effect/typeclass",
		description:
			"Typeclasses and instances for functional programming abstractions.",
		modules: [
			{ name: "Alternative", href: "/docs/api/v3/typeclass/Alternative" },
			{ name: "Applicative", href: "/docs/api/v3/typeclass/Applicative" },
			{ name: "Bicovariant", href: "/docs/api/v3/typeclass/Bicovariant" },
			{ name: "Bounded", href: "/docs/api/v3/typeclass/Bounded" },
			{ name: "Chainable", href: "/docs/api/v3/typeclass/Chainable" },
			{ name: "Contravariant", href: "/docs/api/v3/typeclass/Contravariant" },
			{ name: "Coproduct", href: "/docs/api/v3/typeclass/Coproduct" },
			{ name: "Covariant", href: "/docs/api/v3/typeclass/Covariant" },
			{ name: "data/Array", href: "/docs/api/v3/typeclass/data/Array" },
			{ name: "data/BigInt", href: "/docs/api/v3/typeclass/data/BigInt" },
			{ name: "data/Boolean", href: "/docs/api/v3/typeclass/data/Boolean" },
			{ name: "data/Duration", href: "/docs/api/v3/typeclass/data/Duration" },
			{ name: "data/Effect", href: "/docs/api/v3/typeclass/data/Effect" },
			{ name: "data/Either", href: "/docs/api/v3/typeclass/data/Either" },
			{ name: "data/Identity", href: "/docs/api/v3/typeclass/data/Identity" },
			{ name: "data/Micro", href: "/docs/api/v3/typeclass/data/Micro" },
			{ name: "data/Number", href: "/docs/api/v3/typeclass/data/Number" },
			{ name: "data/Option", href: "/docs/api/v3/typeclass/data/Option" },
			{ name: "data/Ordering", href: "/docs/api/v3/typeclass/data/Ordering" },
			{ name: "data/Predicate", href: "/docs/api/v3/typeclass/data/Predicate" },
			{ name: "data/Record", href: "/docs/api/v3/typeclass/data/Record" },
			{ name: "data/String", href: "/docs/api/v3/typeclass/data/String" },
			{ name: "data/Tuple", href: "/docs/api/v3/typeclass/data/Tuple" },
			{ name: "Filterable", href: "/docs/api/v3/typeclass/Filterable" },
			{ name: "FlatMap", href: "/docs/api/v3/typeclass/FlatMap" },
			{ name: "Foldable", href: "/docs/api/v3/typeclass/Foldable" },
			{ name: "index", href: "/docs/api/v3/typeclass/index" },
			{ name: "Invariant", href: "/docs/api/v3/typeclass/Invariant" },
			{ name: "Monad", href: "/docs/api/v3/typeclass/Monad" },
			{ name: "Monoid", href: "/docs/api/v3/typeclass/Monoid" },
			{ name: "Of", href: "/docs/api/v3/typeclass/Of" },
			{ name: "Pointed", href: "/docs/api/v3/typeclass/Pointed" },
			{ name: "Product", href: "/docs/api/v3/typeclass/Product" },
			{
				name: "SemiAlternative",
				href: "/docs/api/v3/typeclass/SemiAlternative",
			},
			{
				name: "SemiApplicative",
				href: "/docs/api/v3/typeclass/SemiApplicative",
			},
			{ name: "SemiCoproduct", href: "/docs/api/v3/typeclass/SemiCoproduct" },
			{ name: "Semigroup", href: "/docs/api/v3/typeclass/Semigroup" },
			{ name: "SemiProduct", href: "/docs/api/v3/typeclass/SemiProduct" },
			{ name: "Traversable", href: "/docs/api/v3/typeclass/Traversable" },
			{
				name: "TraversableFilterable",
				href: "/docs/api/v3/typeclass/TraversableFilterable",
			},
		],
	},
	{
		slug: "vitest",
		name: "@effect/vitest",
		description: "Vitest integration for testing Effect code.",
		modules: [
			{ name: "index", href: "/docs/api/v3/vitest/index" },
			{ name: "utils", href: "/docs/api/v3/vitest/utils" },
		],
	},
	{
		slug: "workflow",
		name: "@effect/workflow",
		description:
			"Durable workflows with activities, durable clocks, and deferred execution.",
		modules: [
			{ name: "Activity", href: "/docs/api/v3/workflow/Activity" },
			{ name: "DurableClock", href: "/docs/api/v3/workflow/DurableClock" },
			{
				name: "DurableDeferred",
				href: "/docs/api/v3/workflow/DurableDeferred",
			},
			{ name: "DurableQueue", href: "/docs/api/v3/workflow/DurableQueue" },
			{
				name: "DurableRateLimiter",
				href: "/docs/api/v3/workflow/DurableRateLimiter",
			},
			{ name: "index", href: "/docs/api/v3/workflow/index" },
			{ name: "Workflow", href: "/docs/api/v3/workflow/Workflow" },
			{ name: "WorkflowEngine", href: "/docs/api/v3/workflow/WorkflowEngine" },
			{ name: "WorkflowProxy", href: "/docs/api/v3/workflow/WorkflowProxy" },
			{
				name: "WorkflowProxyServer",
				href: "/docs/api/v3/workflow/WorkflowProxyServer",
			},
		],
	},
	{
		slug: "ai",
		name: "@effect/ai",
		description:
			"Provider-agnostic AI toolkit \u2014 language models, embeddings, tools, and MCP servers.",
		modules: [
			{ name: "AiError", href: "/docs/api/v3/ai/AiError" },
			{ name: "Chat", href: "/docs/api/v3/ai/Chat" },
			{ name: "EmbeddingModel", href: "/docs/api/v3/ai/EmbeddingModel" },
			{ name: "IdGenerator", href: "/docs/api/v3/ai/IdGenerator" },
			{ name: "index", href: "/docs/api/v3/ai/index" },
			{ name: "LanguageModel", href: "/docs/api/v3/ai/LanguageModel" },
			{ name: "McpSchema", href: "/docs/api/v3/ai/McpSchema" },
			{ name: "McpServer", href: "/docs/api/v3/ai/McpServer" },
			{ name: "Model", href: "/docs/api/v3/ai/Model" },
			{ name: "Prompt", href: "/docs/api/v3/ai/Prompt" },
			{ name: "Response", href: "/docs/api/v3/ai/Response" },
			{ name: "Telemetry", href: "/docs/api/v3/ai/Telemetry" },
			{ name: "Tokenizer", href: "/docs/api/v3/ai/Tokenizer" },
			{ name: "Tool", href: "/docs/api/v3/ai/Tool" },
			{ name: "Toolkit", href: "/docs/api/v3/ai/Toolkit" },
		],
	},
	{
		slug: "ai-amazon-bedrock",
		name: "@effect/ai-amazon-bedrock",
		description: "Amazon Bedrock provider for the AI toolkit.",
		modules: [
			{
				name: "AmazonBedrockClient",
				href: "/docs/api/v3/ai-amazon-bedrock/AmazonBedrockClient",
			},
			{
				name: "AmazonBedrockConfig",
				href: "/docs/api/v3/ai-amazon-bedrock/AmazonBedrockConfig",
			},
			{
				name: "AmazonBedrockLanguageModel",
				href: "/docs/api/v3/ai-amazon-bedrock/AmazonBedrockLanguageModel",
			},
			{
				name: "AmazonBedrockSchema",
				href: "/docs/api/v3/ai-amazon-bedrock/AmazonBedrockSchema",
			},
			{
				name: "AmazonBedrockTool",
				href: "/docs/api/v3/ai-amazon-bedrock/AmazonBedrockTool",
			},
			{
				name: "EventStreamEncoding",
				href: "/docs/api/v3/ai-amazon-bedrock/EventStreamEncoding",
			},
			{ name: "index", href: "/docs/api/v3/ai-amazon-bedrock/index" },
		],
	},
	{
		slug: "ai-anthropic",
		name: "@effect/ai-anthropic",
		description: "Anthropic provider for the AI toolkit.",
		modules: [
			{
				name: "AnthropicClient",
				href: "/docs/api/v3/ai-anthropic/AnthropicClient",
			},
			{
				name: "AnthropicConfig",
				href: "/docs/api/v3/ai-anthropic/AnthropicConfig",
			},
			{
				name: "AnthropicLanguageModel",
				href: "/docs/api/v3/ai-anthropic/AnthropicLanguageModel",
			},
			{
				name: "AnthropicTokenizer",
				href: "/docs/api/v3/ai-anthropic/AnthropicTokenizer",
			},
			{
				name: "AnthropicTool",
				href: "/docs/api/v3/ai-anthropic/AnthropicTool",
			},
			{ name: "index", href: "/docs/api/v3/ai-anthropic/index" },
		],
	},
	{
		slug: "ai-google",
		name: "@effect/ai-google",
		description: "Google provider for the AI toolkit.",
		modules: [
			{ name: "GoogleClient", href: "/docs/api/v3/ai-google/GoogleClient" },
			{ name: "GoogleConfig", href: "/docs/api/v3/ai-google/GoogleConfig" },
			{
				name: "GoogleLanguageModel",
				href: "/docs/api/v3/ai-google/GoogleLanguageModel",
			},
			{ name: "GoogleTool", href: "/docs/api/v3/ai-google/GoogleTool" },
			{ name: "index", href: "/docs/api/v3/ai-google/index" },
		],
	},
	{
		slug: "ai-openai",
		name: "@effect/ai-openai",
		description: "OpenAI provider for the AI toolkit.",
		modules: [
			{ name: "index", href: "/docs/api/v3/ai-openai/index" },
			{ name: "OpenAiClient", href: "/docs/api/v3/ai-openai/OpenAiClient" },
			{ name: "OpenAiConfig", href: "/docs/api/v3/ai-openai/OpenAiConfig" },
			{
				name: "OpenAiEmbeddingModel",
				href: "/docs/api/v3/ai-openai/OpenAiEmbeddingModel",
			},
			{
				name: "OpenAiLanguageModel",
				href: "/docs/api/v3/ai-openai/OpenAiLanguageModel",
			},
			{
				name: "OpenAiTelemetry",
				href: "/docs/api/v3/ai-openai/OpenAiTelemetry",
			},
			{
				name: "OpenAiTokenizer",
				href: "/docs/api/v3/ai-openai/OpenAiTokenizer",
			},
			{ name: "OpenAiTool", href: "/docs/api/v3/ai-openai/OpenAiTool" },
		],
	},
	{
		slug: "ai-openrouter",
		name: "@effect/ai-openrouter",
		description: "OpenRouter provider for the AI toolkit.",
		modules: [
			{ name: "index", href: "/docs/api/v3/ai-openrouter/index" },
			{
				name: "OpenRouterClient",
				href: "/docs/api/v3/ai-openrouter/OpenRouterClient",
			},
			{
				name: "OpenRouterConfig",
				href: "/docs/api/v3/ai-openrouter/OpenRouterConfig",
			},
			{
				name: "OpenRouterLanguageModel",
				href: "/docs/api/v3/ai-openrouter/OpenRouterLanguageModel",
			},
		],
	},
];

export const API_PACKAGE_GROUPS: { title: string; slugs: string[] }[] = [
	{ title: "Core", slugs: ["effect", "typeclass"] },
	{
		title: "Platform",
		slugs: [
			"platform",
			"platform-browser",
			"platform-bun",
			"platform-node",
			"platform-node-shared",
		],
	},
	{ title: "Distributed", slugs: ["cluster", "rpc", "workflow"] },
	{
		title: "Databases",
		slugs: [
			"sql",
			"sql-clickhouse",
			"sql-d1",
			"sql-drizzle",
			"sql-kysely",
			"sql-libsql",
			"sql-mssql",
			"sql-mysql2",
			"sql-pg",
			"sql-sqlite-bun",
			"sql-sqlite-do",
			"sql-sqlite-node",
			"sql-sqlite-react-native",
			"sql-sqlite-wasm",
		],
	},
	{
		title: "AI",
		slugs: [
			"ai",
			"ai-amazon-bedrock",
			"ai-anthropic",
			"ai-google",
			"ai-openai",
			"ai-openrouter",
		],
	},
	{
		title: "Tooling",
		slugs: [
			"cli",
			"opentelemetry",
			"printer",
			"printer-ansi",
			"vitest",
			"experimental",
		],
	},
];
