// Generated from https://effect-ts.github.io/effect (API reference navigation).
// Package descriptions and thematic groupings are authored by hand.

export type ApiModule = { name: string; href: string };

export type ApiPackage = {
	slug: string;
	name: string;
	description: string;
	modules: ApiModule[];
	/** Optional thematic grouping of modules, keyed by group title. */
	moduleGroups?: { title: string; modules: string[] }[];
};

export const API_PACKAGES: ApiPackage[] = [
	{
		slug: "cli",
		name: "@effect/cli",
		description: "Build polished, type-safe command-line applications with arguments, options, and prompts.",
		modules: [
			{ name: "Args", href: "/docs/api/cli/Args" },
			{ name: "AutoCorrect", href: "/docs/api/cli/AutoCorrect" },
			{ name: "BuiltInOptions", href: "/docs/api/cli/BuiltInOptions" },
			{ name: "CliApp", href: "/docs/api/cli/CliApp" },
			{ name: "CliConfig", href: "/docs/api/cli/CliConfig" },
			{ name: "Command", href: "/docs/api/cli/Command" },
			{ name: "CommandDescriptor", href: "/docs/api/cli/CommandDescriptor" },
			{ name: "CommandDirective", href: "/docs/api/cli/CommandDirective" },
			{ name: "ConfigFile", href: "/docs/api/cli/ConfigFile" },
			{ name: "HelpDoc", href: "/docs/api/cli/HelpDoc" },
			{ name: "HelpDoc/Span", href: "/docs/api/cli/HelpDoc/Span" },
			{ name: "index", href: "/docs/api/cli/index" },
			{ name: "Options", href: "/docs/api/cli/Options" },
			{ name: "Primitive", href: "/docs/api/cli/Primitive" },
			{ name: "Prompt", href: "/docs/api/cli/Prompt" },
			{ name: "Usage", href: "/docs/api/cli/Usage" },
			{ name: "ValidationError", href: "/docs/api/cli/ValidationError" },
		],
	},
	{
		slug: "cluster",
		name: "@effect/cluster",
		description: "Distributed computing with entities, sharding, singletons, and durable messaging.",
		modules: [
			{ name: "ClusterCron", href: "/docs/api/cluster/ClusterCron" },
			{ name: "ClusterError", href: "/docs/api/cluster/ClusterError" },
			{ name: "ClusterMetrics", href: "/docs/api/cluster/ClusterMetrics" },
			{ name: "ClusterSchema", href: "/docs/api/cluster/ClusterSchema" },
			{ name: "ClusterWorkflowEngine", href: "/docs/api/cluster/ClusterWorkflowEngine" },
			{ name: "DeliverAt", href: "/docs/api/cluster/DeliverAt" },
			{ name: "Entity", href: "/docs/api/cluster/Entity" },
			{ name: "EntityAddress", href: "/docs/api/cluster/EntityAddress" },
			{ name: "EntityId", href: "/docs/api/cluster/EntityId" },
			{ name: "EntityProxy", href: "/docs/api/cluster/EntityProxy" },
			{ name: "EntityProxyServer", href: "/docs/api/cluster/EntityProxyServer" },
			{ name: "EntityResource", href: "/docs/api/cluster/EntityResource" },
			{ name: "EntityType", href: "/docs/api/cluster/EntityType" },
			{ name: "Envelope", href: "/docs/api/cluster/Envelope" },
			{ name: "HttpRunner", href: "/docs/api/cluster/HttpRunner" },
			{ name: "index", href: "/docs/api/cluster/index" },
			{ name: "K8sHttpClient", href: "/docs/api/cluster/K8sHttpClient" },
			{ name: "MachineId", href: "/docs/api/cluster/MachineId" },
			{ name: "Message", href: "/docs/api/cluster/Message" },
			{ name: "MessageStorage", href: "/docs/api/cluster/MessageStorage" },
			{ name: "Reply", href: "/docs/api/cluster/Reply" },
			{ name: "Runner", href: "/docs/api/cluster/Runner" },
			{ name: "RunnerAddress", href: "/docs/api/cluster/RunnerAddress" },
			{ name: "RunnerHealth", href: "/docs/api/cluster/RunnerHealth" },
			{ name: "Runners", href: "/docs/api/cluster/Runners" },
			{ name: "RunnerServer", href: "/docs/api/cluster/RunnerServer" },
			{ name: "RunnerStorage", href: "/docs/api/cluster/RunnerStorage" },
			{ name: "ShardId", href: "/docs/api/cluster/ShardId" },
			{ name: "Sharding", href: "/docs/api/cluster/Sharding" },
			{ name: "ShardingConfig", href: "/docs/api/cluster/ShardingConfig" },
			{ name: "ShardingRegistrationEvent", href: "/docs/api/cluster/ShardingRegistrationEvent" },
			{ name: "SingleRunner", href: "/docs/api/cluster/SingleRunner" },
			{ name: "Singleton", href: "/docs/api/cluster/Singleton" },
			{ name: "SingletonAddress", href: "/docs/api/cluster/SingletonAddress" },
			{ name: "Snowflake", href: "/docs/api/cluster/Snowflake" },
			{ name: "SocketRunner", href: "/docs/api/cluster/SocketRunner" },
			{ name: "SqlMessageStorage", href: "/docs/api/cluster/SqlMessageStorage" },
			{ name: "SqlRunnerStorage", href: "/docs/api/cluster/SqlRunnerStorage" },
			{ name: "TestRunner", href: "/docs/api/cluster/TestRunner" },
		],
		moduleGroups: [
			{ title: "Entities", modules: ["Entity", "EntityAddress", "EntityId", "EntityProxy", "EntityProxyServer", "EntityResource", "EntityType", "Singleton", "SingletonAddress"] },
			{ title: "Sharding", modules: ["Sharding", "ShardingConfig", "ShardingRegistrationEvent", "ShardId", "MachineId"] },
			{ title: "Runners", modules: ["Runner", "RunnerAddress", "RunnerHealth", "Runners", "RunnerServer", "RunnerStorage", "HttpRunner", "SocketRunner", "SingleRunner", "TestRunner"] },
			{ title: "Messaging", modules: ["Message", "MessageStorage", "Envelope", "Reply", "DeliverAt", "Snowflake"] },
			{ title: "Storage", modules: ["SqlMessageStorage", "SqlRunnerStorage"] },
			{ title: "Cluster", modules: ["ClusterCron", "ClusterError", "ClusterMetrics", "ClusterSchema", "ClusterWorkflowEngine", "K8sHttpClient", "index"] },
		],
	},
	{
		slug: "effect",
		name: "effect",
		description: "The core Effect library \u2014 data types, concurrency, streams, scheduling, configuration, and more.",
		modules: [
			{ name: "Arbitrary", href: "/docs/api/effect/Arbitrary" },
			{ name: "Array", href: "/docs/api/effect/Array" },
			{ name: "BigDecimal", href: "/docs/api/effect/BigDecimal" },
			{ name: "BigInt", href: "/docs/api/effect/BigInt" },
			{ name: "Boolean", href: "/docs/api/effect/Boolean" },
			{ name: "Brand", href: "/docs/api/effect/Brand" },
			{ name: "Cache", href: "/docs/api/effect/Cache" },
			{ name: "Cause", href: "/docs/api/effect/Cause" },
			{ name: "Channel", href: "/docs/api/effect/Channel" },
			{ name: "ChildExecutorDecision", href: "/docs/api/effect/ChildExecutorDecision" },
			{ name: "Chunk", href: "/docs/api/effect/Chunk" },
			{ name: "Clock", href: "/docs/api/effect/Clock" },
			{ name: "Config", href: "/docs/api/effect/Config" },
			{ name: "ConfigError", href: "/docs/api/effect/ConfigError" },
			{ name: "ConfigProvider", href: "/docs/api/effect/ConfigProvider" },
			{ name: "ConfigProviderPathPatch", href: "/docs/api/effect/ConfigProviderPathPatch" },
			{ name: "Console", href: "/docs/api/effect/Console" },
			{ name: "Context", href: "/docs/api/effect/Context" },
			{ name: "Cron", href: "/docs/api/effect/Cron" },
			{ name: "Data", href: "/docs/api/effect/Data" },
			{ name: "DateTime", href: "/docs/api/effect/DateTime" },
			{ name: "DefaultServices", href: "/docs/api/effect/DefaultServices" },
			{ name: "Deferred", href: "/docs/api/effect/Deferred" },
			{ name: "Differ", href: "/docs/api/effect/Differ" },
			{ name: "Duration", href: "/docs/api/effect/Duration" },
			{ name: "Effect", href: "/docs/api/effect/Effect" },
			{ name: "Effectable", href: "/docs/api/effect/Effectable" },
			{ name: "Either", href: "/docs/api/effect/Either" },
			{ name: "Encoding", href: "/docs/api/effect/Encoding" },
			{ name: "Equal", href: "/docs/api/effect/Equal" },
			{ name: "Equivalence", href: "/docs/api/effect/Equivalence" },
			{ name: "ExecutionPlan", href: "/docs/api/effect/ExecutionPlan" },
			{ name: "ExecutionStrategy", href: "/docs/api/effect/ExecutionStrategy" },
			{ name: "Exit", href: "/docs/api/effect/Exit" },
			{ name: "FastCheck", href: "/docs/api/effect/FastCheck" },
			{ name: "Fiber", href: "/docs/api/effect/Fiber" },
			{ name: "FiberHandle", href: "/docs/api/effect/FiberHandle" },
			{ name: "FiberId", href: "/docs/api/effect/FiberId" },
			{ name: "FiberMap", href: "/docs/api/effect/FiberMap" },
			{ name: "FiberRef", href: "/docs/api/effect/FiberRef" },
			{ name: "FiberRefs", href: "/docs/api/effect/FiberRefs" },
			{ name: "FiberRefsPatch", href: "/docs/api/effect/FiberRefsPatch" },
			{ name: "FiberSet", href: "/docs/api/effect/FiberSet" },
			{ name: "FiberStatus", href: "/docs/api/effect/FiberStatus" },
			{ name: "Function", href: "/docs/api/effect/Function" },
			{ name: "GlobalValue", href: "/docs/api/effect/GlobalValue" },
			{ name: "Graph", href: "/docs/api/effect/Graph" },
			{ name: "GroupBy", href: "/docs/api/effect/GroupBy" },
			{ name: "Hash", href: "/docs/api/effect/Hash" },
			{ name: "HashMap", href: "/docs/api/effect/HashMap" },
			{ name: "HashRing", href: "/docs/api/effect/HashRing" },
			{ name: "HashSet", href: "/docs/api/effect/HashSet" },
			{ name: "HKT", href: "/docs/api/effect/HKT" },
			{ name: "index", href: "/docs/api/effect/index" },
			{ name: "Inspectable", href: "/docs/api/effect/Inspectable" },
			{ name: "Iterable", href: "/docs/api/effect/Iterable" },
			{ name: "JSONSchema", href: "/docs/api/effect/JSONSchema" },
			{ name: "KeyedPool", href: "/docs/api/effect/KeyedPool" },
			{ name: "Layer", href: "/docs/api/effect/Layer" },
			{ name: "LayerMap", href: "/docs/api/effect/LayerMap" },
			{ name: "List", href: "/docs/api/effect/List" },
			{ name: "Logger", href: "/docs/api/effect/Logger" },
			{ name: "LogLevel", href: "/docs/api/effect/LogLevel" },
			{ name: "LogSpan", href: "/docs/api/effect/LogSpan" },
			{ name: "Mailbox", href: "/docs/api/effect/Mailbox" },
			{ name: "ManagedRuntime", href: "/docs/api/effect/ManagedRuntime" },
			{ name: "Match", href: "/docs/api/effect/Match" },
			{ name: "MergeDecision", href: "/docs/api/effect/MergeDecision" },
			{ name: "MergeState", href: "/docs/api/effect/MergeState" },
			{ name: "MergeStrategy", href: "/docs/api/effect/MergeStrategy" },
			{ name: "Metric", href: "/docs/api/effect/Metric" },
			{ name: "MetricBoundaries", href: "/docs/api/effect/MetricBoundaries" },
			{ name: "MetricHook", href: "/docs/api/effect/MetricHook" },
			{ name: "MetricKey", href: "/docs/api/effect/MetricKey" },
			{ name: "MetricKeyType", href: "/docs/api/effect/MetricKeyType" },
			{ name: "MetricLabel", href: "/docs/api/effect/MetricLabel" },
			{ name: "MetricPair", href: "/docs/api/effect/MetricPair" },
			{ name: "MetricPolling", href: "/docs/api/effect/MetricPolling" },
			{ name: "MetricRegistry", href: "/docs/api/effect/MetricRegistry" },
			{ name: "MetricState", href: "/docs/api/effect/MetricState" },
			{ name: "Micro", href: "/docs/api/effect/Micro" },
			{ name: "ModuleVersion", href: "/docs/api/effect/ModuleVersion" },
			{ name: "MutableHashMap", href: "/docs/api/effect/MutableHashMap" },
			{ name: "MutableHashSet", href: "/docs/api/effect/MutableHashSet" },
			{ name: "MutableList", href: "/docs/api/effect/MutableList" },
			{ name: "MutableQueue", href: "/docs/api/effect/MutableQueue" },
			{ name: "MutableRef", href: "/docs/api/effect/MutableRef" },
			{ name: "NonEmptyIterable", href: "/docs/api/effect/NonEmptyIterable" },
			{ name: "Number", href: "/docs/api/effect/Number" },
			{ name: "Option", href: "/docs/api/effect/Option" },
			{ name: "Order", href: "/docs/api/effect/Order" },
			{ name: "Ordering", href: "/docs/api/effect/Ordering" },
			{ name: "ParseResult", href: "/docs/api/effect/ParseResult" },
			{ name: "PartitionedSemaphore", href: "/docs/api/effect/PartitionedSemaphore" },
			{ name: "Pipeable", href: "/docs/api/effect/Pipeable" },
			{ name: "Pool", href: "/docs/api/effect/Pool" },
			{ name: "Predicate", href: "/docs/api/effect/Predicate" },
			{ name: "Pretty", href: "/docs/api/effect/Pretty" },
			{ name: "PrimaryKey", href: "/docs/api/effect/PrimaryKey" },
			{ name: "PubSub", href: "/docs/api/effect/PubSub" },
			{ name: "Queue", href: "/docs/api/effect/Queue" },
			{ name: "Random", href: "/docs/api/effect/Random" },
			{ name: "RateLimiter", href: "/docs/api/effect/RateLimiter" },
			{ name: "RcMap", href: "/docs/api/effect/RcMap" },
			{ name: "RcRef", href: "/docs/api/effect/RcRef" },
			{ name: "Readable", href: "/docs/api/effect/Readable" },
			{ name: "Record", href: "/docs/api/effect/Record" },
			{ name: "Redacted", href: "/docs/api/effect/Redacted" },
			{ name: "RedBlackTree", href: "/docs/api/effect/RedBlackTree" },
			{ name: "Ref", href: "/docs/api/effect/Ref" },
			{ name: "RegExp", href: "/docs/api/effect/RegExp" },
			{ name: "Reloadable", href: "/docs/api/effect/Reloadable" },
			{ name: "Request", href: "/docs/api/effect/Request" },
			{ name: "RequestBlock", href: "/docs/api/effect/RequestBlock" },
			{ name: "RequestResolver", href: "/docs/api/effect/RequestResolver" },
			{ name: "Resource", href: "/docs/api/effect/Resource" },
			{ name: "Runtime", href: "/docs/api/effect/Runtime" },
			{ name: "RuntimeFlags", href: "/docs/api/effect/RuntimeFlags" },
			{ name: "RuntimeFlagsPatch", href: "/docs/api/effect/RuntimeFlagsPatch" },
			{ name: "Schedule", href: "/docs/api/effect/Schedule" },
			{ name: "ScheduleDecision", href: "/docs/api/effect/ScheduleDecision" },
			{ name: "ScheduleInterval", href: "/docs/api/effect/ScheduleInterval" },
			{ name: "ScheduleIntervals", href: "/docs/api/effect/ScheduleIntervals" },
			{ name: "Scheduler", href: "/docs/api/effect/Scheduler" },
			{ name: "Schema", href: "/docs/api/effect/Schema" },
			{ name: "SchemaAST", href: "/docs/api/effect/SchemaAST" },
			{ name: "Scope", href: "/docs/api/effect/Scope" },
			{ name: "ScopedCache", href: "/docs/api/effect/ScopedCache" },
			{ name: "ScopedRef", href: "/docs/api/effect/ScopedRef" },
			{ name: "Secret", href: "/docs/api/effect/Secret" },
			{ name: "SingleProducerAsyncInput", href: "/docs/api/effect/SingleProducerAsyncInput" },
			{ name: "Sink", href: "/docs/api/effect/Sink" },
			{ name: "SortedMap", href: "/docs/api/effect/SortedMap" },
			{ name: "SortedSet", href: "/docs/api/effect/SortedSet" },
			{ name: "STM", href: "/docs/api/effect/STM" },
			{ name: "Stream", href: "/docs/api/effect/Stream" },
			{ name: "Streamable", href: "/docs/api/effect/Streamable" },
			{ name: "StreamEmit", href: "/docs/api/effect/StreamEmit" },
			{ name: "StreamHaltStrategy", href: "/docs/api/effect/StreamHaltStrategy" },
			{ name: "String", href: "/docs/api/effect/String" },
			{ name: "Struct", href: "/docs/api/effect/Struct" },
			{ name: "Subscribable", href: "/docs/api/effect/Subscribable" },
			{ name: "SubscriptionRef", href: "/docs/api/effect/SubscriptionRef" },
			{ name: "Supervisor", href: "/docs/api/effect/Supervisor" },
			{ name: "Symbol", href: "/docs/api/effect/Symbol" },
			{ name: "SynchronizedRef", href: "/docs/api/effect/SynchronizedRef" },
			{ name: "Take", href: "/docs/api/effect/Take" },
			{ name: "TArray", href: "/docs/api/effect/TArray" },
			{ name: "TDeferred", href: "/docs/api/effect/TDeferred" },
			{ name: "TestAnnotation", href: "/docs/api/effect/TestAnnotation" },
			{ name: "TestAnnotationMap", href: "/docs/api/effect/TestAnnotationMap" },
			{ name: "TestAnnotations", href: "/docs/api/effect/TestAnnotations" },
			{ name: "TestClock", href: "/docs/api/effect/TestClock" },
			{ name: "TestConfig", href: "/docs/api/effect/TestConfig" },
			{ name: "TestContext", href: "/docs/api/effect/TestContext" },
			{ name: "TestLive", href: "/docs/api/effect/TestLive" },
			{ name: "TestServices", href: "/docs/api/effect/TestServices" },
			{ name: "TestSized", href: "/docs/api/effect/TestSized" },
			{ name: "TMap", href: "/docs/api/effect/TMap" },
			{ name: "TPriorityQueue", href: "/docs/api/effect/TPriorityQueue" },
			{ name: "TPubSub", href: "/docs/api/effect/TPubSub" },
			{ name: "TQueue", href: "/docs/api/effect/TQueue" },
			{ name: "Tracer", href: "/docs/api/effect/Tracer" },
			{ name: "TRandom", href: "/docs/api/effect/TRandom" },
			{ name: "TReentrantLock", href: "/docs/api/effect/TReentrantLock" },
			{ name: "TRef", href: "/docs/api/effect/TRef" },
			{ name: "Trie", href: "/docs/api/effect/Trie" },
			{ name: "TSemaphore", href: "/docs/api/effect/TSemaphore" },
			{ name: "TSet", href: "/docs/api/effect/TSet" },
			{ name: "TSubscriptionRef", href: "/docs/api/effect/TSubscriptionRef" },
			{ name: "Tuple", href: "/docs/api/effect/Tuple" },
			{ name: "Types", href: "/docs/api/effect/Types" },
			{ name: "Unify", href: "/docs/api/effect/Unify" },
			{ name: "UpstreamPullRequest", href: "/docs/api/effect/UpstreamPullRequest" },
			{ name: "UpstreamPullStrategy", href: "/docs/api/effect/UpstreamPullStrategy" },
			{ name: "Utils", href: "/docs/api/effect/Utils" },
		],
	},
	{
		slug: "experimental",
		name: "@effect/experimental",
		description: "Experimental modules under active development \u2014 APIs may change without notice.",
		modules: [
			{ name: "DevTools", href: "/docs/api/experimental/DevTools" },
			{ name: "DevTools/Client", href: "/docs/api/experimental/DevTools/Client" },
			{ name: "DevTools/Domain", href: "/docs/api/experimental/DevTools/Domain" },
			{ name: "DevTools/Server", href: "/docs/api/experimental/DevTools/Server" },
			{ name: "Event", href: "/docs/api/experimental/Event" },
			{ name: "EventGroup", href: "/docs/api/experimental/EventGroup" },
			{ name: "EventJournal", href: "/docs/api/experimental/EventJournal" },
			{ name: "EventLog", href: "/docs/api/experimental/EventLog" },
			{ name: "EventLogEncryption", href: "/docs/api/experimental/EventLogEncryption" },
			{ name: "EventLogRemote", href: "/docs/api/experimental/EventLogRemote" },
			{ name: "EventLogServer", href: "/docs/api/experimental/EventLogServer" },
			{ name: "EventLogServer/Cloudflare", href: "/docs/api/experimental/EventLogServer/Cloudflare" },
			{ name: "index", href: "/docs/api/experimental/index" },
			{ name: "Machine", href: "/docs/api/experimental/Machine" },
			{ name: "Machine/Procedure", href: "/docs/api/experimental/Machine/Procedure" },
			{ name: "Machine/ProcedureList", href: "/docs/api/experimental/Machine/ProcedureList" },
			{ name: "Machine/SerializableProcedureList", href: "/docs/api/experimental/Machine/SerializableProcedureList" },
			{ name: "PersistedCache", href: "/docs/api/experimental/PersistedCache" },
			{ name: "PersistedQueue", href: "/docs/api/experimental/PersistedQueue" },
			{ name: "PersistedQueue/Redis", href: "/docs/api/experimental/PersistedQueue/Redis" },
			{ name: "Persistence", href: "/docs/api/experimental/Persistence" },
			{ name: "Persistence/Lmdb", href: "/docs/api/experimental/Persistence/Lmdb" },
			{ name: "Persistence/Redis", href: "/docs/api/experimental/Persistence/Redis" },
			{ name: "RateLimiter", href: "/docs/api/experimental/RateLimiter" },
			{ name: "RateLimiter/Redis", href: "/docs/api/experimental/RateLimiter/Redis" },
			{ name: "Reactivity", href: "/docs/api/experimental/Reactivity" },
			{ name: "RequestResolver", href: "/docs/api/experimental/RequestResolver" },
			{ name: "Sse", href: "/docs/api/experimental/Sse" },
			{ name: "VariantSchema", href: "/docs/api/experimental/VariantSchema" },
		],
	},
	{
		slug: "opentelemetry",
		name: "@effect/opentelemetry",
		description: "OpenTelemetry integration for tracing, metrics, and logging.",
		modules: [
			{ name: "index", href: "/docs/api/opentelemetry/index" },
			{ name: "Logger", href: "/docs/api/opentelemetry/Logger" },
			{ name: "Metrics", href: "/docs/api/opentelemetry/Metrics" },
			{ name: "NodeSdk", href: "/docs/api/opentelemetry/NodeSdk" },
			{ name: "Otlp", href: "/docs/api/opentelemetry/Otlp" },
			{ name: "OtlpLogger", href: "/docs/api/opentelemetry/OtlpLogger" },
			{ name: "OtlpMetrics", href: "/docs/api/opentelemetry/OtlpMetrics" },
			{ name: "OtlpResource", href: "/docs/api/opentelemetry/OtlpResource" },
			{ name: "OtlpSerialization", href: "/docs/api/opentelemetry/OtlpSerialization" },
			{ name: "OtlpTracer", href: "/docs/api/opentelemetry/OtlpTracer" },
			{ name: "Resource", href: "/docs/api/opentelemetry/Resource" },
			{ name: "Tracer", href: "/docs/api/opentelemetry/Tracer" },
			{ name: "WebSdk", href: "/docs/api/opentelemetry/WebSdk" },
		],
	},
	{
		slug: "platform",
		name: "@effect/platform",
		description: "Platform-agnostic abstractions for HTTP, file systems, sockets, workers, and more.",
		modules: [
			{ name: "ChannelSchema", href: "/docs/api/platform/ChannelSchema" },
			{ name: "Command", href: "/docs/api/platform/Command" },
			{ name: "CommandExecutor", href: "/docs/api/platform/CommandExecutor" },
			{ name: "Cookies", href: "/docs/api/platform/Cookies" },
			{ name: "Effectify", href: "/docs/api/platform/Effectify" },
			{ name: "Error", href: "/docs/api/platform/Error" },
			{ name: "Etag", href: "/docs/api/platform/Etag" },
			{ name: "FetchHttpClient", href: "/docs/api/platform/FetchHttpClient" },
			{ name: "FileSystem", href: "/docs/api/platform/FileSystem" },
			{ name: "Headers", href: "/docs/api/platform/Headers" },
			{ name: "HttpApi", href: "/docs/api/platform/HttpApi" },
			{ name: "HttpApiBuilder", href: "/docs/api/platform/HttpApiBuilder" },
			{ name: "HttpApiClient", href: "/docs/api/platform/HttpApiClient" },
			{ name: "HttpApiEndpoint", href: "/docs/api/platform/HttpApiEndpoint" },
			{ name: "HttpApiError", href: "/docs/api/platform/HttpApiError" },
			{ name: "HttpApiGroup", href: "/docs/api/platform/HttpApiGroup" },
			{ name: "HttpApiMiddleware", href: "/docs/api/platform/HttpApiMiddleware" },
			{ name: "HttpApiScalar", href: "/docs/api/platform/HttpApiScalar" },
			{ name: "HttpApiSchema", href: "/docs/api/platform/HttpApiSchema" },
			{ name: "HttpApiSecurity", href: "/docs/api/platform/HttpApiSecurity" },
			{ name: "HttpApiSwagger", href: "/docs/api/platform/HttpApiSwagger" },
			{ name: "HttpApp", href: "/docs/api/platform/HttpApp" },
			{ name: "HttpBody", href: "/docs/api/platform/HttpBody" },
			{ name: "HttpClient", href: "/docs/api/platform/HttpClient" },
			{ name: "HttpClientError", href: "/docs/api/platform/HttpClientError" },
			{ name: "HttpClientRequest", href: "/docs/api/platform/HttpClientRequest" },
			{ name: "HttpClientResponse", href: "/docs/api/platform/HttpClientResponse" },
			{ name: "HttpIncomingMessage", href: "/docs/api/platform/HttpIncomingMessage" },
			{ name: "HttpLayerRouter", href: "/docs/api/platform/HttpLayerRouter" },
			{ name: "HttpMethod", href: "/docs/api/platform/HttpMethod" },
			{ name: "HttpMiddleware", href: "/docs/api/platform/HttpMiddleware" },
			{ name: "HttpMultiplex", href: "/docs/api/platform/HttpMultiplex" },
			{ name: "HttpPlatform", href: "/docs/api/platform/HttpPlatform" },
			{ name: "HttpRouter", href: "/docs/api/platform/HttpRouter" },
			{ name: "HttpServer", href: "/docs/api/platform/HttpServer" },
			{ name: "HttpServerError", href: "/docs/api/platform/HttpServerError" },
			{ name: "HttpServerRequest", href: "/docs/api/platform/HttpServerRequest" },
			{ name: "HttpServerRespondable", href: "/docs/api/platform/HttpServerRespondable" },
			{ name: "HttpServerResponse", href: "/docs/api/platform/HttpServerResponse" },
			{ name: "HttpTraceContext", href: "/docs/api/platform/HttpTraceContext" },
			{ name: "index", href: "/docs/api/platform/index" },
			{ name: "KeyValueStore", href: "/docs/api/platform/KeyValueStore" },
			{ name: "MsgPack", href: "/docs/api/platform/MsgPack" },
			{ name: "Multipart", href: "/docs/api/platform/Multipart" },
			{ name: "Ndjson", href: "/docs/api/platform/Ndjson" },
			{ name: "OpenApi", href: "/docs/api/platform/OpenApi" },
			{ name: "OpenApiJsonSchema", href: "/docs/api/platform/OpenApiJsonSchema" },
			{ name: "Path", href: "/docs/api/platform/Path" },
			{ name: "PlatformConfigProvider", href: "/docs/api/platform/PlatformConfigProvider" },
			{ name: "PlatformLogger", href: "/docs/api/platform/PlatformLogger" },
			{ name: "Runtime", href: "/docs/api/platform/Runtime" },
			{ name: "Socket", href: "/docs/api/platform/Socket" },
			{ name: "SocketServer", href: "/docs/api/platform/SocketServer" },
			{ name: "Template", href: "/docs/api/platform/Template" },
			{ name: "Terminal", href: "/docs/api/platform/Terminal" },
			{ name: "Transferable", href: "/docs/api/platform/Transferable" },
			{ name: "Url", href: "/docs/api/platform/Url" },
			{ name: "UrlParams", href: "/docs/api/platform/UrlParams" },
			{ name: "Worker", href: "/docs/api/platform/Worker" },
			{ name: "WorkerError", href: "/docs/api/platform/WorkerError" },
			{ name: "WorkerRunner", href: "/docs/api/platform/WorkerRunner" },
		],
	},
	{
		slug: "platform-browser",
		name: "@effect/platform-browser",
		description: "Browser implementations of the platform abstractions.",
		modules: [
			{ name: "BrowserHttpClient", href: "/docs/api/platform-browser/BrowserHttpClient" },
			{ name: "BrowserKeyValueStore", href: "/docs/api/platform-browser/BrowserKeyValueStore" },
			{ name: "BrowserRuntime", href: "/docs/api/platform-browser/BrowserRuntime" },
			{ name: "BrowserSocket", href: "/docs/api/platform-browser/BrowserSocket" },
			{ name: "BrowserStream", href: "/docs/api/platform-browser/BrowserStream" },
			{ name: "BrowserWorker", href: "/docs/api/platform-browser/BrowserWorker" },
			{ name: "BrowserWorkerRunner", href: "/docs/api/platform-browser/BrowserWorkerRunner" },
			{ name: "Clipboard", href: "/docs/api/platform-browser/Clipboard" },
			{ name: "Geolocation", href: "/docs/api/platform-browser/Geolocation" },
			{ name: "index", href: "/docs/api/platform-browser/index" },
			{ name: "Permissions", href: "/docs/api/platform-browser/Permissions" },
		],
	},
	{
		slug: "platform-bun",
		name: "@effect/platform-bun",
		description: "Bun implementations of the platform abstractions.",
		modules: [
			{ name: "BunClusterHttp", href: "/docs/api/platform-bun/BunClusterHttp" },
			{ name: "BunClusterSocket", href: "/docs/api/platform-bun/BunClusterSocket" },
			{ name: "BunCommandExecutor", href: "/docs/api/platform-bun/BunCommandExecutor" },
			{ name: "BunContext", href: "/docs/api/platform-bun/BunContext" },
			{ name: "BunFileSystem", href: "/docs/api/platform-bun/BunFileSystem" },
			{ name: "BunFileSystem/ParcelWatcher", href: "/docs/api/platform-bun/BunFileSystem/ParcelWatcher" },
			{ name: "BunHttpPlatform", href: "/docs/api/platform-bun/BunHttpPlatform" },
			{ name: "BunHttpServer", href: "/docs/api/platform-bun/BunHttpServer" },
			{ name: "BunHttpServerRequest", href: "/docs/api/platform-bun/BunHttpServerRequest" },
			{ name: "BunKeyValueStore", href: "/docs/api/platform-bun/BunKeyValueStore" },
			{ name: "BunMultipart", href: "/docs/api/platform-bun/BunMultipart" },
			{ name: "BunPath", href: "/docs/api/platform-bun/BunPath" },
			{ name: "BunRuntime", href: "/docs/api/platform-bun/BunRuntime" },
			{ name: "BunSink", href: "/docs/api/platform-bun/BunSink" },
			{ name: "BunSocket", href: "/docs/api/platform-bun/BunSocket" },
			{ name: "BunSocketServer", href: "/docs/api/platform-bun/BunSocketServer" },
			{ name: "BunStream", href: "/docs/api/platform-bun/BunStream" },
			{ name: "BunTerminal", href: "/docs/api/platform-bun/BunTerminal" },
			{ name: "BunWorker", href: "/docs/api/platform-bun/BunWorker" },
			{ name: "BunWorkerRunner", href: "/docs/api/platform-bun/BunWorkerRunner" },
			{ name: "index", href: "/docs/api/platform-bun/index" },
		],
	},
	{
		slug: "platform-node",
		name: "@effect/platform-node",
		description: "Node.js implementations of the platform abstractions.",
		modules: [
			{ name: "index", href: "/docs/api/platform-node/index" },
			{ name: "NodeClusterHttp", href: "/docs/api/platform-node/NodeClusterHttp" },
			{ name: "NodeClusterSocket", href: "/docs/api/platform-node/NodeClusterSocket" },
			{ name: "NodeCommandExecutor", href: "/docs/api/platform-node/NodeCommandExecutor" },
			{ name: "NodeContext", href: "/docs/api/platform-node/NodeContext" },
			{ name: "NodeFileSystem", href: "/docs/api/platform-node/NodeFileSystem" },
			{ name: "NodeFileSystem/ParcelWatcher", href: "/docs/api/platform-node/NodeFileSystem/ParcelWatcher" },
			{ name: "NodeHttpClient", href: "/docs/api/platform-node/NodeHttpClient" },
			{ name: "NodeHttpPlatform", href: "/docs/api/platform-node/NodeHttpPlatform" },
			{ name: "NodeHttpServer", href: "/docs/api/platform-node/NodeHttpServer" },
			{ name: "NodeHttpServerRequest", href: "/docs/api/platform-node/NodeHttpServerRequest" },
			{ name: "NodeKeyValueStore", href: "/docs/api/platform-node/NodeKeyValueStore" },
			{ name: "NodeMultipart", href: "/docs/api/platform-node/NodeMultipart" },
			{ name: "NodePath", href: "/docs/api/platform-node/NodePath" },
			{ name: "NodeRuntime", href: "/docs/api/platform-node/NodeRuntime" },
			{ name: "NodeSink", href: "/docs/api/platform-node/NodeSink" },
			{ name: "NodeSocket", href: "/docs/api/platform-node/NodeSocket" },
			{ name: "NodeSocketServer", href: "/docs/api/platform-node/NodeSocketServer" },
			{ name: "NodeStream", href: "/docs/api/platform-node/NodeStream" },
			{ name: "NodeTerminal", href: "/docs/api/platform-node/NodeTerminal" },
			{ name: "NodeWorker", href: "/docs/api/platform-node/NodeWorker" },
			{ name: "NodeWorkerRunner", href: "/docs/api/platform-node/NodeWorkerRunner" },
			{ name: "Undici", href: "/docs/api/platform-node/Undici" },
		],
	},
	{
		slug: "platform-node-shared",
		name: "@effect/platform-node-shared",
		description: "Shared internals for Node.js-compatible platform implementations.",
		modules: [
			{ name: "NodeClusterSocket", href: "/docs/api/platform-node-shared/NodeClusterSocket" },
			{ name: "NodeCommandExecutor", href: "/docs/api/platform-node-shared/NodeCommandExecutor" },
			{ name: "NodeFileSystem", href: "/docs/api/platform-node-shared/NodeFileSystem" },
			{ name: "NodeFileSystem/ParcelWatcher", href: "/docs/api/platform-node-shared/NodeFileSystem/ParcelWatcher" },
			{ name: "NodeKeyValueStore", href: "/docs/api/platform-node-shared/NodeKeyValueStore" },
			{ name: "NodeMultipart", href: "/docs/api/platform-node-shared/NodeMultipart" },
			{ name: "NodePath", href: "/docs/api/platform-node-shared/NodePath" },
			{ name: "NodeRuntime", href: "/docs/api/platform-node-shared/NodeRuntime" },
			{ name: "NodeSink", href: "/docs/api/platform-node-shared/NodeSink" },
			{ name: "NodeSocket", href: "/docs/api/platform-node-shared/NodeSocket" },
			{ name: "NodeSocketServer", href: "/docs/api/platform-node-shared/NodeSocketServer" },
			{ name: "NodeStream", href: "/docs/api/platform-node-shared/NodeStream" },
			{ name: "NodeTerminal", href: "/docs/api/platform-node-shared/NodeTerminal" },
		],
	},
	{
		slug: "printer",
		name: "@effect/printer",
		description: "A pretty-printer for rendering structured documents to text.",
		modules: [
			{ name: "Doc", href: "/docs/api/printer/Doc" },
			{ name: "DocStream", href: "/docs/api/printer/DocStream" },
			{ name: "DocTree", href: "/docs/api/printer/DocTree" },
			{ name: "Flatten", href: "/docs/api/printer/Flatten" },
			{ name: "index", href: "/docs/api/printer/index" },
			{ name: "Layout", href: "/docs/api/printer/Layout" },
			{ name: "Optimize", href: "/docs/api/printer/Optimize" },
			{ name: "PageWidth", href: "/docs/api/printer/PageWidth" },
		],
	},
	{
		slug: "printer-ansi",
		name: "@effect/printer-ansi",
		description: "ANSI terminal rendering with colors and styles for the printer.",
		modules: [
			{ name: "Ansi", href: "/docs/api/printer-ansi/Ansi" },
			{ name: "AnsiDoc", href: "/docs/api/printer-ansi/AnsiDoc" },
			{ name: "Color", href: "/docs/api/printer-ansi/Color" },
			{ name: "index", href: "/docs/api/printer-ansi/index" },
		],
	},
	{
		slug: "rpc",
		name: "@effect/rpc",
		description: "Type-safe remote procedure calls between client and server.",
		modules: [
			{ name: "index", href: "/docs/api/rpc/index" },
			{ name: "Rpc", href: "/docs/api/rpc/Rpc" },
			{ name: "RpcClient", href: "/docs/api/rpc/RpcClient" },
			{ name: "RpcClientError", href: "/docs/api/rpc/RpcClientError" },
			{ name: "RpcGroup", href: "/docs/api/rpc/RpcGroup" },
			{ name: "RpcMessage", href: "/docs/api/rpc/RpcMessage" },
			{ name: "RpcMiddleware", href: "/docs/api/rpc/RpcMiddleware" },
			{ name: "RpcSchema", href: "/docs/api/rpc/RpcSchema" },
			{ name: "RpcSerialization", href: "/docs/api/rpc/RpcSerialization" },
			{ name: "RpcServer", href: "/docs/api/rpc/RpcServer" },
			{ name: "RpcTest", href: "/docs/api/rpc/RpcTest" },
			{ name: "RpcWorker", href: "/docs/api/rpc/RpcWorker" },
		],
	},
	{
		slug: "sql",
		name: "@effect/sql",
		description: "SQL toolkit with clients, statements, migrations, models, and resolvers.",
		modules: [
			{ name: "index", href: "/docs/api/sql/index" },
			{ name: "Migrator", href: "/docs/api/sql/Migrator" },
			{ name: "Migrator/FileSystem", href: "/docs/api/sql/Migrator/FileSystem" },
			{ name: "Model", href: "/docs/api/sql/Model" },
			{ name: "SqlClient", href: "/docs/api/sql/SqlClient" },
			{ name: "SqlConnection", href: "/docs/api/sql/SqlConnection" },
			{ name: "SqlError", href: "/docs/api/sql/SqlError" },
			{ name: "SqlEventJournal", href: "/docs/api/sql/SqlEventJournal" },
			{ name: "SqlEventLogServer", href: "/docs/api/sql/SqlEventLogServer" },
			{ name: "SqlPersistedQueue", href: "/docs/api/sql/SqlPersistedQueue" },
			{ name: "SqlResolver", href: "/docs/api/sql/SqlResolver" },
			{ name: "SqlSchema", href: "/docs/api/sql/SqlSchema" },
			{ name: "SqlStream", href: "/docs/api/sql/SqlStream" },
			{ name: "Statement", href: "/docs/api/sql/Statement" },
		],
	},
	{
		slug: "sql-clickhouse",
		name: "@effect/sql-clickhouse",
		description: "ClickHouse client and migrator.",
		modules: [
			{ name: "ClickhouseClient", href: "/docs/api/sql-clickhouse/ClickhouseClient" },
			{ name: "ClickhouseMigrator", href: "/docs/api/sql-clickhouse/ClickhouseMigrator" },
			{ name: "index", href: "/docs/api/sql-clickhouse/index" },
		],
	},
	{
		slug: "sql-d1",
		name: "@effect/sql-d1",
		description: "Cloudflare D1 client.",
		modules: [
			{ name: "D1Client", href: "/docs/api/sql-d1/D1Client" },
			{ name: "index", href: "/docs/api/sql-d1/index" },
		],
	},
	{
		slug: "sql-drizzle",
		name: "@effect/sql-drizzle",
		description: "Drizzle ORM integration for Postgres, MySQL, and SQLite.",
		modules: [
			{ name: "Mysql", href: "/docs/api/sql-drizzle/Mysql" },
			{ name: "Pg", href: "/docs/api/sql-drizzle/Pg" },
			{ name: "Sqlite", href: "/docs/api/sql-drizzle/Sqlite" },
		],
	},
	{
		slug: "sql-kysely",
		name: "@effect/sql-kysely",
		description: "Kysely query-builder integration for Postgres, MySQL, MSSQL, and SQLite.",
		modules: [
			{ name: "Kysely", href: "/docs/api/sql-kysely/Kysely" },
			{ name: "Mssql", href: "/docs/api/sql-kysely/Mssql" },
			{ name: "Mysql", href: "/docs/api/sql-kysely/Mysql" },
			{ name: "patch.types", href: "/docs/api/sql-kysely/patch.types" },
			{ name: "Pg", href: "/docs/api/sql-kysely/Pg" },
			{ name: "Sqlite", href: "/docs/api/sql-kysely/Sqlite" },
		],
	},
	{
		slug: "sql-libsql",
		name: "@effect/sql-libsql",
		description: "libSQL client and migrator.",
		modules: [
			{ name: "index", href: "/docs/api/sql-libsql/index" },
			{ name: "LibsqlClient", href: "/docs/api/sql-libsql/LibsqlClient" },
			{ name: "LibsqlMigrator", href: "/docs/api/sql-libsql/LibsqlMigrator" },
		],
	},
	{
		slug: "sql-mssql",
		name: "@effect/sql-mssql",
		description: "Microsoft SQL Server client and migrator.",
		modules: [
			{ name: "index", href: "/docs/api/sql-mssql/index" },
			{ name: "MssqlClient", href: "/docs/api/sql-mssql/MssqlClient" },
			{ name: "MssqlMigrator", href: "/docs/api/sql-mssql/MssqlMigrator" },
			{ name: "Parameter", href: "/docs/api/sql-mssql/Parameter" },
			{ name: "Procedure", href: "/docs/api/sql-mssql/Procedure" },
		],
	},
	{
		slug: "sql-mysql2",
		name: "@effect/sql-mysql2",
		description: "MySQL client and migrator built on mysql2.",
		modules: [
			{ name: "index", href: "/docs/api/sql-mysql2/index" },
			{ name: "MysqlClient", href: "/docs/api/sql-mysql2/MysqlClient" },
			{ name: "MysqlMigrator", href: "/docs/api/sql-mysql2/MysqlMigrator" },
		],
	},
	{
		slug: "sql-pg",
		name: "@effect/sql-pg",
		description: "PostgreSQL client and migrator.",
		modules: [
			{ name: "index", href: "/docs/api/sql-pg/index" },
			{ name: "PgClient", href: "/docs/api/sql-pg/PgClient" },
			{ name: "PgMigrator", href: "/docs/api/sql-pg/PgMigrator" },
		],
	},
	{
		slug: "sql-sqlite-bun",
		name: "@effect/sql-sqlite-bun",
		description: "SQLite client and migrator for Bun.",
		modules: [
			{ name: "index", href: "/docs/api/sql-sqlite-bun/index" },
			{ name: "SqliteClient", href: "/docs/api/sql-sqlite-bun/SqliteClient" },
			{ name: "SqliteMigrator", href: "/docs/api/sql-sqlite-bun/SqliteMigrator" },
		],
	},
	{
		slug: "sql-sqlite-do",
		name: "@effect/sql-sqlite-do",
		description: "SQLite client and migrator for Cloudflare Durable Objects.",
		modules: [
			{ name: "index", href: "/docs/api/sql-sqlite-do/index" },
			{ name: "SqliteClient", href: "/docs/api/sql-sqlite-do/SqliteClient" },
			{ name: "SqliteMigrator", href: "/docs/api/sql-sqlite-do/SqliteMigrator" },
		],
	},
	{
		slug: "sql-sqlite-node",
		name: "@effect/sql-sqlite-node",
		description: "SQLite client and migrator for Node.js.",
		modules: [
			{ name: "index", href: "/docs/api/sql-sqlite-node/index" },
			{ name: "SqliteClient", href: "/docs/api/sql-sqlite-node/SqliteClient" },
			{ name: "SqliteMigrator", href: "/docs/api/sql-sqlite-node/SqliteMigrator" },
		],
	},
	{
		slug: "sql-sqlite-react-native",
		name: "@effect/sql-sqlite-react-native",
		description: "SQLite client and migrator for React Native.",
		modules: [
			{ name: "index", href: "/docs/api/sql-sqlite-react-native/index" },
			{ name: "SqliteClient", href: "/docs/api/sql-sqlite-react-native/SqliteClient" },
			{ name: "SqliteMigrator", href: "/docs/api/sql-sqlite-react-native/SqliteMigrator" },
		],
	},
	{
		slug: "sql-sqlite-wasm",
		name: "@effect/sql-sqlite-wasm",
		description: "SQLite client and migrator running on WebAssembly (OPFS).",
		modules: [
			{ name: "index", href: "/docs/api/sql-sqlite-wasm/index" },
			{ name: "OpfsWorker", href: "/docs/api/sql-sqlite-wasm/OpfsWorker" },
			{ name: "sqlite-wasm", href: "/docs/api/sql-sqlite-wasm/sqlite-wasm" },
			{ name: "SqliteClient", href: "/docs/api/sql-sqlite-wasm/SqliteClient" },
			{ name: "SqliteMigrator", href: "/docs/api/sql-sqlite-wasm/SqliteMigrator" },
		],
	},
	{
		slug: "typeclass",
		name: "@effect/typeclass",
		description: "Typeclasses and instances for functional programming abstractions.",
		modules: [
			{ name: "Alternative", href: "/docs/api/typeclass/Alternative" },
			{ name: "Applicative", href: "/docs/api/typeclass/Applicative" },
			{ name: "Bicovariant", href: "/docs/api/typeclass/Bicovariant" },
			{ name: "Bounded", href: "/docs/api/typeclass/Bounded" },
			{ name: "Chainable", href: "/docs/api/typeclass/Chainable" },
			{ name: "Contravariant", href: "/docs/api/typeclass/Contravariant" },
			{ name: "Coproduct", href: "/docs/api/typeclass/Coproduct" },
			{ name: "Covariant", href: "/docs/api/typeclass/Covariant" },
			{ name: "data/Array", href: "/docs/api/typeclass/data/Array" },
			{ name: "data/BigInt", href: "/docs/api/typeclass/data/BigInt" },
			{ name: "data/Boolean", href: "/docs/api/typeclass/data/Boolean" },
			{ name: "data/Duration", href: "/docs/api/typeclass/data/Duration" },
			{ name: "data/Effect", href: "/docs/api/typeclass/data/Effect" },
			{ name: "data/Either", href: "/docs/api/typeclass/data/Either" },
			{ name: "data/Identity", href: "/docs/api/typeclass/data/Identity" },
			{ name: "data/Micro", href: "/docs/api/typeclass/data/Micro" },
			{ name: "data/Number", href: "/docs/api/typeclass/data/Number" },
			{ name: "data/Option", href: "/docs/api/typeclass/data/Option" },
			{ name: "data/Ordering", href: "/docs/api/typeclass/data/Ordering" },
			{ name: "data/Predicate", href: "/docs/api/typeclass/data/Predicate" },
			{ name: "data/Record", href: "/docs/api/typeclass/data/Record" },
			{ name: "data/String", href: "/docs/api/typeclass/data/String" },
			{ name: "data/Tuple", href: "/docs/api/typeclass/data/Tuple" },
			{ name: "Filterable", href: "/docs/api/typeclass/Filterable" },
			{ name: "FlatMap", href: "/docs/api/typeclass/FlatMap" },
			{ name: "Foldable", href: "/docs/api/typeclass/Foldable" },
			{ name: "index", href: "/docs/api/typeclass/index" },
			{ name: "Invariant", href: "/docs/api/typeclass/Invariant" },
			{ name: "Monad", href: "/docs/api/typeclass/Monad" },
			{ name: "Monoid", href: "/docs/api/typeclass/Monoid" },
			{ name: "Of", href: "/docs/api/typeclass/Of" },
			{ name: "Pointed", href: "/docs/api/typeclass/Pointed" },
			{ name: "Product", href: "/docs/api/typeclass/Product" },
			{ name: "SemiAlternative", href: "/docs/api/typeclass/SemiAlternative" },
			{ name: "SemiApplicative", href: "/docs/api/typeclass/SemiApplicative" },
			{ name: "SemiCoproduct", href: "/docs/api/typeclass/SemiCoproduct" },
			{ name: "Semigroup", href: "/docs/api/typeclass/Semigroup" },
			{ name: "SemiProduct", href: "/docs/api/typeclass/SemiProduct" },
			{ name: "Traversable", href: "/docs/api/typeclass/Traversable" },
			{ name: "TraversableFilterable", href: "/docs/api/typeclass/TraversableFilterable" },
		],
	},
	{
		slug: "vitest",
		name: "@effect/vitest",
		description: "Vitest integration for testing Effect code.",
		modules: [
			{ name: "index", href: "/docs/api/vitest/index" },
			{ name: "utils", href: "/docs/api/vitest/utils" },
		],
	},
	{
		slug: "workflow",
		name: "@effect/workflow",
		description: "Durable workflows with activities, durable clocks, and deferred execution.",
		modules: [
			{ name: "Activity", href: "/docs/api/workflow/Activity" },
			{ name: "DurableClock", href: "/docs/api/workflow/DurableClock" },
			{ name: "DurableDeferred", href: "/docs/api/workflow/DurableDeferred" },
			{ name: "DurableQueue", href: "/docs/api/workflow/DurableQueue" },
			{ name: "DurableRateLimiter", href: "/docs/api/workflow/DurableRateLimiter" },
			{ name: "index", href: "/docs/api/workflow/index" },
			{ name: "Workflow", href: "/docs/api/workflow/Workflow" },
			{ name: "WorkflowEngine", href: "/docs/api/workflow/WorkflowEngine" },
			{ name: "WorkflowProxy", href: "/docs/api/workflow/WorkflowProxy" },
			{ name: "WorkflowProxyServer", href: "/docs/api/workflow/WorkflowProxyServer" },
		],
	},
	{
		slug: "ai",
		name: "@effect/ai",
		description: "Provider-agnostic AI toolkit \u2014 language models, embeddings, tools, and MCP servers.",
		modules: [
			{ name: "AiError", href: "/docs/api/ai/AiError" },
			{ name: "Chat", href: "/docs/api/ai/Chat" },
			{ name: "EmbeddingModel", href: "/docs/api/ai/EmbeddingModel" },
			{ name: "IdGenerator", href: "/docs/api/ai/IdGenerator" },
			{ name: "index", href: "/docs/api/ai/index" },
			{ name: "LanguageModel", href: "/docs/api/ai/LanguageModel" },
			{ name: "McpSchema", href: "/docs/api/ai/McpSchema" },
			{ name: "McpServer", href: "/docs/api/ai/McpServer" },
			{ name: "Model", href: "/docs/api/ai/Model" },
			{ name: "Prompt", href: "/docs/api/ai/Prompt" },
			{ name: "Response", href: "/docs/api/ai/Response" },
			{ name: "Telemetry", href: "/docs/api/ai/Telemetry" },
			{ name: "Tokenizer", href: "/docs/api/ai/Tokenizer" },
			{ name: "Tool", href: "/docs/api/ai/Tool" },
			{ name: "Toolkit", href: "/docs/api/ai/Toolkit" },
		],
	},
	{
		slug: "ai-amazon-bedrock",
		name: "@effect/ai-amazon-bedrock",
		description: "Amazon Bedrock provider for the AI toolkit.",
		modules: [
			{ name: "AmazonBedrockClient", href: "/docs/api/ai-amazon-bedrock/AmazonBedrockClient" },
			{ name: "AmazonBedrockConfig", href: "/docs/api/ai-amazon-bedrock/AmazonBedrockConfig" },
			{ name: "AmazonBedrockLanguageModel", href: "/docs/api/ai-amazon-bedrock/AmazonBedrockLanguageModel" },
			{ name: "AmazonBedrockSchema", href: "/docs/api/ai-amazon-bedrock/AmazonBedrockSchema" },
			{ name: "AmazonBedrockTool", href: "/docs/api/ai-amazon-bedrock/AmazonBedrockTool" },
			{ name: "EventStreamEncoding", href: "/docs/api/ai-amazon-bedrock/EventStreamEncoding" },
			{ name: "index", href: "/docs/api/ai-amazon-bedrock/index" },
		],
	},
	{
		slug: "ai-anthropic",
		name: "@effect/ai-anthropic",
		description: "Anthropic provider for the AI toolkit.",
		modules: [
			{ name: "AnthropicClient", href: "/docs/api/ai-anthropic/AnthropicClient" },
			{ name: "AnthropicConfig", href: "/docs/api/ai-anthropic/AnthropicConfig" },
			{ name: "AnthropicLanguageModel", href: "/docs/api/ai-anthropic/AnthropicLanguageModel" },
			{ name: "AnthropicTokenizer", href: "/docs/api/ai-anthropic/AnthropicTokenizer" },
			{ name: "AnthropicTool", href: "/docs/api/ai-anthropic/AnthropicTool" },
			{ name: "index", href: "/docs/api/ai-anthropic/index" },
		],
	},
	{
		slug: "ai-google",
		name: "@effect/ai-google",
		description: "Google provider for the AI toolkit.",
		modules: [
			{ name: "GoogleClient", href: "/docs/api/ai-google/GoogleClient" },
			{ name: "GoogleConfig", href: "/docs/api/ai-google/GoogleConfig" },
			{ name: "GoogleLanguageModel", href: "/docs/api/ai-google/GoogleLanguageModel" },
			{ name: "GoogleTool", href: "/docs/api/ai-google/GoogleTool" },
			{ name: "index", href: "/docs/api/ai-google/index" },
		],
	},
	{
		slug: "ai-openai",
		name: "@effect/ai-openai",
		description: "OpenAI provider for the AI toolkit.",
		modules: [
			{ name: "index", href: "/docs/api/ai-openai/index" },
			{ name: "OpenAiClient", href: "/docs/api/ai-openai/OpenAiClient" },
			{ name: "OpenAiConfig", href: "/docs/api/ai-openai/OpenAiConfig" },
			{ name: "OpenAiEmbeddingModel", href: "/docs/api/ai-openai/OpenAiEmbeddingModel" },
			{ name: "OpenAiLanguageModel", href: "/docs/api/ai-openai/OpenAiLanguageModel" },
			{ name: "OpenAiTelemetry", href: "/docs/api/ai-openai/OpenAiTelemetry" },
			{ name: "OpenAiTokenizer", href: "/docs/api/ai-openai/OpenAiTokenizer" },
			{ name: "OpenAiTool", href: "/docs/api/ai-openai/OpenAiTool" },
		],
	},
	{
		slug: "ai-openrouter",
		name: "@effect/ai-openrouter",
		description: "OpenRouter provider for the AI toolkit.",
		modules: [
			{ name: "index", href: "/docs/api/ai-openrouter/index" },
			{ name: "OpenRouterClient", href: "/docs/api/ai-openrouter/OpenRouterClient" },
			{ name: "OpenRouterConfig", href: "/docs/api/ai-openrouter/OpenRouterConfig" },
			{ name: "OpenRouterLanguageModel", href: "/docs/api/ai-openrouter/OpenRouterLanguageModel" },
		],
	},
];

export const API_PACKAGE_GROUPS: { title: string; slugs: string[] }[] = [
	{ title: "Core", slugs: ["effect", "typeclass"] },
	{ title: "Platform", slugs: ["platform", "platform-browser", "platform-bun", "platform-node", "platform-node-shared"] },
	{ title: "Distributed", slugs: ["cluster", "rpc", "workflow"] },
	{ title: "Databases", slugs: ["sql", "sql-clickhouse", "sql-d1", "sql-drizzle", "sql-kysely", "sql-libsql", "sql-mssql", "sql-mysql2", "sql-pg", "sql-sqlite-bun", "sql-sqlite-do", "sql-sqlite-node", "sql-sqlite-react-native", "sql-sqlite-wasm"] },
	{ title: "AI", slugs: ["ai", "ai-amazon-bedrock", "ai-anthropic", "ai-google", "ai-openai", "ai-openrouter"] },
	{ title: "Tooling", slugs: ["cli", "opentelemetry", "printer", "printer-ansi", "vitest", "experimental"] },
];
