import {
	ArrowDown,
	ArrowLeft,
	ArrowRight,
	ArrowUp,
	ArrowUpDown,
	ArrowUpRight,
	BookOpen,
	Bot,
	Braces,
	Building2,
	Calendar,
	CalendarCheck,
	ChartLine,
	Check,
	ChevronDown,
	ChevronLeft,
	ChevronRight,
	CircleAlert,
	CircleCheck,
	CirclePlay,
	CircleX,
	ClipboardList,
	Clock,
	Copy,
	CornerRightDown,
	Download,
	ExternalLink,
	FileCheck,
	FileSearch,
	FileText,
	FlaskConical,
	FolderGit2,
	GitBranch,
	GraduationCap,
	HeartHandshake,
	History,
	Layers,
	LayoutGrid,
	LifeBuoy,
	Link,
	MapPin,
	Maximize2,
	Megaphone,
	Menu,
	Mic,
	Minimize2,
	Monitor,
	Moon,
	Network,
	Newspaper,
	Palette,
	Play,
	Plug,
	Plus,
	Presentation,
	Radio,
	RefreshCw,
	Rocket,
	Rss,
	ScrollText,
	Search,
	Shapes,
	ShieldCheck,
	Shirt,
	Sparkles,
	Sun,
	ThumbsDown,
	ThumbsUp,
	Ticket,
	User,
	Users,
	Wrench,
	X,
} from "lucide-react";
import type { ComponentPropsWithoutRef } from "react";

/**
 * Site-wide icon component backed by Lucide.
 *
 * Renders at 1em (via the `icon-inline` class in globals.css) so icons are
 * sized and colored with the same `text-*` utilities the old Remix icon
 * font used. Brand glyphs (Discord, GitHub, X, …) are not covered here —
 * those intentionally remain on the Remix icon font.
 */
const ICONS = {
	"arrow-down": ArrowDown,
	"arrow-left": ArrowLeft,
	"arrow-right": ArrowRight,
	"arrow-up": ArrowUp,
	"arrow-up-down": ArrowUpDown,
	"arrow-up-right": ArrowUpRight,
	"book-open": BookOpen,
	bot: Bot,
	braces: Braces,
	building: Building2,
	calendar: Calendar,
	"calendar-check": CalendarCheck,
	"chart-line": ChartLine,
	check: Check,
	"chevron-down": ChevronDown,
	"chevron-left": ChevronLeft,
	"chevron-right": ChevronRight,
	"circle-alert": CircleAlert,
	"circle-check": CircleCheck,
	"circle-play": CirclePlay,
	"circle-x": CircleX,
	"clipboard-list": ClipboardList,
	clock: Clock,
	copy: Copy,
	"corner-right-down": CornerRightDown,
	download: Download,
	"external-link": ExternalLink,
	"file-check": FileCheck,
	"file-search": FileSearch,
	"file-text": FileText,
	flask: FlaskConical,
	"folder-git": FolderGit2,
	"git-branch": GitBranch,
	"graduation-cap": GraduationCap,
	"heart-handshake": HeartHandshake,
	history: History,
	layers: Layers,
	"layout-grid": LayoutGrid,
	"life-buoy": LifeBuoy,
	link: Link,
	"map-pin": MapPin,
	maximize: Maximize2,
	megaphone: Megaphone,
	menu: Menu,
	mic: Mic,
	minimize: Minimize2,
	monitor: Monitor,
	moon: Moon,
	network: Network,
	newspaper: Newspaper,
	palette: Palette,
	play: Play,
	plug: Plug,
	plus: Plus,
	presentation: Presentation,
	radio: Radio,
	"refresh-cw": RefreshCw,
	rocket: Rocket,
	rss: Rss,
	"scroll-text": ScrollText,
	search: Search,
	shapes: Shapes,
	"shield-check": ShieldCheck,
	shirt: Shirt,
	sparkles: Sparkles,
	sun: Sun,
	"thumbs-down": ThumbsDown,
	"thumbs-up": ThumbsUp,
	ticket: Ticket,
	user: User,
	users: Users,
	wrench: Wrench,
	x: X,
} as const;

export type IconName = keyof typeof ICONS;

export interface IconProps extends ComponentPropsWithoutRef<"svg"> {
	name: IconName;
}

export function Icon({ name, className, ...props }: IconProps) {
	const Glyph = ICONS[name];
	return (
		<Glyph
			className={className ? `icon-inline ${className}` : "icon-inline"}
			{...props}
		/>
	);
}
